# -*- coding: utf-8 -*-
"""Peak_ground_acceleration_regression_with_psa_clusters - pre split.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10T4OC4a4-j9mY2Txqh9jqdlppk2GLwB4

Accurate estimation of Peak Ground Acceleration (PGA) is crucial for assessing the potential destructiveness of seismic events and guiding infrastructure inspection and resource allocation. While many PGA forecasting methods rely on local soil data, such information is often unavailable due to high acquisition costs.

Our study aims to show that an artificial intelligence ensemble approach can improve PGA prediction by using machine learning clustering techniques applied to Pseudo-Spectral Accelerations (PSA) data as an alternative to missing soil information.

This Notebook processes data from the National Autonomous University of Mexico (UNAM). To access this data, a request must be made directly to UNAM.

The Notebook requires four files:
* earthquakes_pga.csv
  * Columns: ['date', 'time', 'magnitude', 'institution', 'entity', 'station_key',
       'station_name', 'peak_ground_acceleration', 'quality', 'file',
       'epicentral_distance', 'depth', 'earthquake_latitude',
       'earthquake_longitude', 'location_reference', 'station_latitude',
       'station_longitude', 'duration', 'incidence_angle',
       'hypocentral_distance', 'azimuth',
       'angle_to_the_nearest_horizontal_sensor',
       'calculated_epicentral_distance', 'calculated_hypocentral_distance',
       'calculated_incidence_angle', 'source_off_shore', 'calculated_azimuth']
* earthquakes_psa.csv
  * This file has PSAs from seismic stations, with 1000 samples each, arranged in columns. The first column has the index of each sample and each subsequent column represents the PSA of an axis of a seismic station, with NS to indicate the North-South axis, EW to indicate the East-West axis and V to indicate the vertical axis. The first columns are: ['period', 'ACAP8509191-EW', 'ACAP8509191-NS', 'ACAP8509191-V', 'ACAS8509191-EW', 'ACAS8509191-NS', 'ACAS8509191-V', 'APAT8509191-EW', 'APAT8509191-NS', 'APAT8509191-V', ...]
* mex_admbndl_admALL_govmex_itos_20210618.shp
  * Its a shape file used to plot maps. Found here https://data.humdata.org/dataset/cod-ab-mex?
* mex_admbndl_admALL_govmex_itos_20210618.shx
  * Its a shape file used to plot maps. Found here https://data.humdata.org/dataset/cod-ab-mex?

#Setup
"""

!pip install -q -U keras-tuner

pip install cartopy

pip install optuna

!pip install gdown

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import math

import geopandas as gpd

from sklearn.neighbors import LocalOutlierFactor

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import MinMaxScaler

from scipy.stats import randint, uniform

from sklearn.cluster import KMeans

from yellowbrick.cluster import SilhouetteVisualizer

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

from sklearn.impute import SimpleImputer

from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import ElasticNet
from sklearn.ensemble import RandomForestRegressor

import keras_tuner as kt

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, KFold

from sklearn.metrics import mean_squared_error, root_mean_squared_error

import tensorflow as tf
import keras

from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import r2_score

from scipy import stats


import pickle
import joblib
import os

import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER


import xgboost as xgb

import sklearn

import optuna
from sklearn.model_selection import cross_val_score

import copy

load_trained_models = False
hiperparameters_tuning = False

tf.random.set_seed(42)

raw_earthquakes_pga_url = 'https://raw.githubusercontent.com/galdir/PGA_regression_with_PSA_clusters/main/earthquakes_pga.csv'

df_raw = pd.read_csv(raw_earthquakes_pga_url)
print(df_raw.shape)

#raw_earthquakes_psa_url = 'https://raw.githubusercontent.com/galdir/PGA_regression_with_PSA_clusters/main/earthquakes_psa.csv'
raw_earthquakes_psa_url = 'https://raw.githubusercontent.com/galdir/PGA_regression_with_PSA_clusters/main/earthquakes_psa_earthquakeid.csv'

df_psa_merged=pd.read_csv(raw_earthquakes_psa_url)
print(df_psa_merged.shape)

df_psa_merged.head()

df_raw.describe()

!wget 'https://github.com/galdir/PGA_regression_with_PSA_clusters/raw/refs/heads/main/ne_110m_admin_0_countries.shp'

!wget 'https://github.com/galdir/PGA_regression_with_PSA_clusters/raw/refs/heads/main/ne_110m_admin_0_countries.shx'

#!gdown --id 1hwy0mZlP8128W_vghZYFlXkzdNTo5Fmh

#!unzip paper_1_results.zip

"""# Remove registers from stations without psa data

In the PSA dataset, there were records that did not have signals for all 3 directions, and they were removed. Therefore, we need to remove those records from the PGA dataset.
"""

columns = df_psa_merged.columns
earthquake_ids = []
station_earthquakeids = []

for column in columns:
  if(column == 'period(s)'):
    continue
  station = column.split('-')[0]
  id = column.split('-')[1][:14]
  earthquake_ids.append(id)
  station_earthquakeid = station + '-' + id
  station_earthquakeids.append(station_earthquakeid)

earthquake_ids_set = set(earthquake_ids)
station_earthquakeid_set = set(station_earthquakeids)

len(earthquake_ids_set)

len(station_earthquakeid_set)

df_raw.head()

df_raw['earthquake_id'] = (df_raw['date'].str.replace('-', '', regex=False) +
                            df_raw['time'].str.replace(':', '', regex=False))

display(df_raw[['date', 'time', 'earthquake_id']].head())

earthquake_id_pga_set = set(df_raw['earthquake_id'])
len(earthquake_id_pga_set)

df_raw['station_earthquakeid'] = df_raw['station_key'] + '-' + df_raw['earthquake_id']
station_earthquakeid_pga_set = set(df_raw['station_earthquakeid'])
len(station_earthquakeid_pga_set)

# Records in PSA but missing in PGA
missing_in_pga = station_earthquakeid_set - station_earthquakeid_pga_set
print(f'Records in PSA but missing in PGA ({len(missing_in_pga)}):')
print(missing_in_pga)

# Records in PGA but missing in PSA
missing_in_psa = station_earthquakeid_pga_set - station_earthquakeid_set
print(f'\nRecords in PGA but missing in PSA ({len(missing_in_psa)}):')
print(missing_in_psa)

df_stations_with_PSA = df_raw.query('station_earthquakeid in @station_earthquakeid_set')

df_stations_with_PSA.index

df_stations_with_PSA.reset_index(inplace=True, drop=True)

df_stations_with_PSA.head()

df = df_stations_with_PSA

df.shape

#station_keys_set = psa_station_keys_set

"""# Data Description and Analysis"""

df.columns

df.info()

df.station_key.unique().shape

df.date.max()

df.date =  pd.to_datetime(df.copy().date)

fig, axs = plt.subplots(4, 3, figsize=(10, 12))

plt.subplots_adjust(hspace=0.4, wspace=0.3)  # Aumentei o espaçamento entre os subplots

sns.histplot(data=df, x="magnitude", kde=True, ax=axs[0, 0])
axs[0,0].set(xlabel="Magnitude (Mw)")

sns.histplot(data=df, x="peak_ground_acceleration", kde=True, ax=axs[0, 1])
axs[0,1].set(xlabel="Peak ground acceleration (cm/s$^2$)")

sns.histplot(data=df, x="depth", kde=True, ax=axs[0, 2])
axs[0,2].set(xlabel="Depth (km)")

sns.histplot(data=df, x="earthquake_latitude", kde=True, ax=axs[1, 0])
axs[1,0].set(xlabel="Earthquake Latitude (°)")

sns.histplot(data=df, x="earthquake_longitude", kde=True, ax=axs[1, 1])
axs[1,1].set(xlabel="Earthquake Longitude (°)")

sns.histplot(data=df, x="station_latitude", kde=True, ax=axs[1, 2])
axs[1,2].set(xlabel="Station Latitude (°)")

sns.histplot(data=df, x="station_longitude", kde=True, ax=axs[2, 0])
axs[2, 0].set(xlabel="Station Latitude (°)")

sns.histplot(data=df, x="calculated_epicentral_distance", kde=True, ax=axs[2, 1])
axs[2, 1].set(xlabel="Epicentral Distance (km)")

sns.histplot(data=df, x="incidence_angle", kde=True, ax=axs[2, 2])
axs[2, 2].set(xlabel="Incidence Angle (°)")

sns.histplot(data=df, x="calculated_azimuth", kde=True, ax=axs[3, 0])
axs[3, 0].set(xlabel="Azimuth (°)")

sns.histplot(data=df, x="date", kde=True, bins=8, ax=axs[3, 1])
axs[3, 1].set(xlabel="Date")
# Rotacionar os rótulos do eixo x em 45 graus
axs[3, 1].tick_params(axis='x', rotation=45)

sns.histplot(data=df, x="calculated_hypocentral_distance", kde=True, ax=axs[3, 2])
axs[3, 2].set(xlabel="Hypocentral Distance (km)")

sns.pairplot(df[['magnitude','peak_ground_acceleration', 'calculated_epicentral_distance']])

"""## mapS"""

df.columns

locations = [
    [-99.1332, 19.4326, "Mexico City"],
]

map_file = 'ne_110m_admin_0_countries.shp'


world = gpd.read_file(map_file)

fig, ax1 = plt.subplots(figsize=(6, 4))

world.plot(ax=ax1, edgecolor='black', facecolor='green', linewidth=1, zorder=1, alpha=0.5)

sns.scatterplot(ax=ax1,
                    data=df,
                    x='earthquake_longitude',
                    y='earthquake_latitude',
                    size='magnitude',
                    hue='magnitude',
                    sizes=(40, 400),
                    zorder=2,
                    palette=sns.color_palette("Reds", as_cmap=True),
                    marker=(8,1,0))

sns.scatterplot(ax=ax1,
                data=df,
                x='station_longitude',
                y='station_latitude',
                zorder=3,
                color='black',
                s=30,
                label='Seismic Station')


ax1.xaxis.set_major_locator(ticker.MultipleLocator(2))  # Intervalo de 2 graus
ax1.yaxis.set_major_locator(ticker.MultipleLocator(1))  # Intervalo de 1 grau

def longitude_formatter(x, p):
    return f'{x}°W'

def latitude_formatter(x, p):
    return f'{x}°N'

ax1.xaxis.set_major_formatter(ticker.FuncFormatter(longitude_formatter))
ax1.yaxis.set_major_formatter(ticker.FuncFormatter(latitude_formatter))

plt.xticks(rotation=45)

ax1.set_xlabel('Longitude', labelpad=10)
ax1.set_ylabel('Latitude', labelpad=10)
plt.xlim([-106, -90])
plt.ylim([13, 22])

plt.legend(frameon=True)

plt.tight_layout()

plt.show()

"""## One event"""

one_event = df[df['date']=='2017-09-19 00:00:00']

one_event.shape

# Faça o plot
fig, ax1 = plt.subplots(figsize=(12, 4))

# Plote o contorno do México
world.plot(ax=ax1, edgecolor='black', facecolor='green', linewidth=1, zorder=1, alpha=0.5)

# Adicionar marcadores para cada localização
for lon, lat, name in locations:
    ax1.plot(lon, lat, 'ko', markersize=3)
    ax1.text(lon, lat, name, color='w', fontsize=8, ha='right', va='bottom')


#ax1 = map.plot(figsize=(8, 6), alpha=0.5)
#ax1.set(xlabel='Longitude', ylabel='Latitude')

sns.scatterplot(ax=ax1,
                data=one_event,
                x='earthquake_longitude',
                y='earthquake_latitude',
                color='red',
                s=1000,
                zorder=2,
                #palette=pal,
                marker=(8,1,0))

sns.scatterplot(ax=ax1,
                data=one_event,
                x='station_longitude',
                y='station_latitude',
                zorder=2,
                hue='peak_ground_acceleration',
                size='peak_ground_acceleration',
                palette=sns.color_palette("flare", as_cmap=True),
                sizes=(20, 200))
plt.xlim([-99, -97.5])
plt.ylim([18, 19.2])

# Definir intervalos para os ticks
ax1.xaxis.set_major_locator(ticker.MultipleLocator(2))  # Intervalo de 2 graus
ax1.yaxis.set_major_locator(ticker.MultipleLocator(1))  # Intervalo de 1 grau

# Formatar os labels com o símbolo de grau
def longitude_formatter(x, p):
    return f'{x}°W'

def latitude_formatter(x, p):
    return f'{x}°N'

ax1.xaxis.set_major_formatter(ticker.FuncFormatter(longitude_formatter))
ax1.yaxis.set_major_formatter(ticker.FuncFormatter(latitude_formatter))

# Rotacionar os labels do eixo x para melhor legibilidade
#plt.xticks(rotation=45)

# Ajustar os limites e labels
ax1.set_xlabel('Longitude', labelpad=10)
ax1.set_ylabel('Latitude', labelpad=10)

# Ajustar o layout para evitar cortes
#plt.tight_layout()


plt.legend(frameon=True, title='Peak Ground Acceleration', loc='lower right')

plt.show()

"""##PSA"""

df_psa_merged.shape

df_psa_merged.info()

print(list(df_psa_merged.columns))

plt.figure(figsize=(4, 3))
plt.plot(df_psa_merged['period(s)'], df_psa_merged.iloc[:, 1:-1])
plt.xlabel('Period (s)')
plt.ylabel('Acceleration (cm/s $^2$)')
plt.show()

df_psa_merged.columns

indexs_v = []
indexs_ew = []
indexs_ns = []

for column in df_psa_merged.columns:
  if column == 'period(s)':
    continue
  orientation = column.split("-")[-1]
  if orientation == 'V':
    indexs_v.append(column)
  elif orientation == 'EW':
    indexs_ew.append(column)
  elif orientation == 'NS':
    indexs_ns.append(column)
  else:
    print('unknown orientation')

fig, axs = plt.subplots(3, 1, figsize=(3,6))

axs[0].plot(df_psa_merged['period(s)'].values, df_psa_merged[indexs_v].values)
axs[0].set_xlabel('Period (s)')
axs[0].set_ylabel('Acceleration (cm/s $^2$)')
axs[0].set_title('Vertical signals')

axs[1].plot(df_psa_merged['period(s)'].values, df_psa_merged[indexs_ew].values)
axs[1].set_xlabel('Period (s)')
axs[1].set_ylabel('Acceleration (cm/s $^2$)')
axs[1].set_title('East-West signals')

axs[2].plot(df_psa_merged['period(s)'].values, df_psa_merged[indexs_ns].values)
axs[2].set_xlabel('Period (s)')
axs[2].set_ylabel('Acceleration (cm/s $^2$)')
axs[2].set_title('North-South signals')

plt.tight_layout()

plt.show()

columns = df_psa_merged.columns


fig, axs = plt.subplots(3, 1, figsize=(3,9))

indexs_station = []

for i in range(len(columns)):
  actual_station_key = columns[i][:4]
  if actual_station_key == 'CALE':
    indexs_station.append(i)
    break

print(indexs_station)

axs[0].plot(df_psa_merged['period(s)'].values, df_psa_merged.iloc[:, indexs_station].values)
axs[0].set_xlabel('Period (s)')
axs[0].set_ylabel('Acceleration (cm/s $^2$)')



indexs_station = []

for i in range(len(columns)):
  actual_station_key = columns[i][:4]
  if actual_station_key == 'ACAD':
    indexs_station.append(i)
    break

axs[1].plot(df_psa_merged['period(s)'], df_psa_merged.iloc[:, indexs_station])
axs[1].set_xlabel('Period (s)')
axs[1].set_ylabel('Acceleration (cm/s $^2$)')



indexs_station = []


for i in range(len(columns)):
  actual_station_key = columns[i][:4]
  if actual_station_key == 'ACAS':
    indexs_station.append(i)
    break

axs[2].plot(df_psa_merged['period(s)'], df_psa_merged.iloc[:, indexs_station])
axs[2].set_xlabel('Period (s)')
axs[2].set_ylabel('Acceleration (cm/s $^2$)')

plt.tight_layout()

plt.show()

columns = df_psa_merged.columns


fig, axs = plt.subplots(1, 2, figsize=(8,4))

indexs_station = []

for i in range(len(columns)):
  actual_station_key = columns[i][:4]
  if actual_station_key == 'CALE':
    indexs_station.append(i)

print(indexs_station)

axs[0].plot(df_psa_merged['period(s)'].values, df_psa_merged.iloc[:, indexs_station].values)
axs[0].set_xlabel('Period (s)')
axs[0].set_ylabel('Acceleration (cm/s $^2$)')

indexs_station = []


for i in range(len(columns)):
  actual_station_key = columns[i][:4]
  if actual_station_key == 'ACAD':
    indexs_station.append(i)

axs[1].plot(df_psa_merged['period(s)'], df_psa_merged.iloc[:, indexs_station])
axs[1].set_xlabel('Period (s)')
axs[1].set_ylabel('Acceleration (cm/s $^2$)')

plt.tight_layout()

plt.show()

"""# Preprocessing

## Feature engineering
"""

sns.histplot(x=df.incidence_angle, kde=True)

df = df.assign(log_incidence_angle=np.log(df.calculated_incidence_angle))

ax = sns.histplot(x=df.log_incidence_angle, kde=True)
ax.set(xlabel='Log Incidence Angle')

sns.histplot(x=(df.magnitude), kde=True)

df["magnitude_cat"] = pd.cut(df["magnitude"],
                             bins=[0., 6.08, 6.5, 7.2, np.inf],
                             #bins=[0., 6.04, 6.3, 6.7, 7.2, np.inf],
                             labels=[1, 2, 3, 4, ])

ax = sns.histplot(x=(df.magnitude_cat))

ax.set(xlabel='Magnitude Category')

df["magnitude_cat"].value_counts()

sns.histplot(x=(df.peak_ground_acceleration), kde=True)

df["peak_ground_acceleration_cat"] = pd.cut(df.peak_ground_acceleration,
                                            bins=[0., 2, 4, 6, 10, 18, 30, 80, np.inf],
                                            labels=[1, 2, 3, 4, 5, 6, 7, 8])

sns.histplot(x=(df.peak_ground_acceleration_cat))

sns.histplot(x=(df.calculated_epicentral_distance), kde=True)

df["calculated_epicentral_distance_cat"] = pd.cut(df.calculated_epicentral_distance,
                                                  bins=[0., 130, 200, 280, 330, 430, np.inf],
                                                  labels=[1, 2, 3, 4, 5, 6])
sns.histplot(x=(df.calculated_epicentral_distance_cat))

sns.histplot(x=(df.depth), kde=True)

df["depth_cat"] = pd.cut(df.depth,
                         bins=[0., 10, 16, 30, 46, np.inf],
                         labels=[1, 2, 3, 4, 5])
sns.histplot(x=(df.depth_cat))

"""##Split"""

df.columns

# 1. Contar quantos registros cada earthquake_id possui
# O .sample(frac=1) embaralha os IDs aleatoriamente para evitar viés
eq_counts = df['earthquake_id'].value_counts().sample(frac=1, random_state=42)

# 2. Calcular a soma cumulativa e a porcentagem que cada ID representa no total de linhas
cumulative_records = eq_counts.cumsum()
total_records = len(df)
cumulative_percentage = cumulative_records / total_records

# 3. Separar os IDs: tudo que estiver até 80% do volume total de dados vai para treino
train_ids = eq_counts[cumulative_percentage <= 0.8].index
test_ids = eq_counts[cumulative_percentage > 0.8].index

# 4. Criar os datasets de treino e teste
train_set = df[df['earthquake_id'].isin(train_ids)].copy()
test_set = df[df['earthquake_id'].isin(test_ids)].copy()

# --- Verificações ---
print(f'Total unique earthquakes: {len(eq_counts)}')
print(f'Earthquakes in train: {len(train_ids)}')
print(f'Earthquakes in test: {len(test_ids)}')
print("-" * 30)
print(f'Total records: {total_records}')
print(f'Train records: {len(train_set)} ({len(train_set)/total_records:.1%})')
print(f'Test records: {len(test_set)} ({len(test_set)/total_records:.1%})')
print("-" * 30)

# Verification: check if there is any overlap
overlap = set(train_set['earthquake_id']).intersection(set(test_set['earthquake_id']))
print(f'Overlap IDs: {overlap}')

df_psa_merged.columns

train_set["earthquake_id"].values

# 1. Garantir que os IDs estão no formato string para a busca de texto
train_ids_str = set(str(x) for x in train_ids)
test_ids_str = set(str(x) for x in test_ids)

# 2. Inicializar as listas de colunas com a coluna comum a ambos
train_cols = ['period(s)']
test_cols = ['period(s)']
unmatched_cols = [] # Para checagem de erros

# 3. Iterar pelas colunas e distribuir entre treino e teste
for col in df_psa_merged.columns:
    if col == 'period(s)':
        continue

    # Verifica se algum dos IDs de treino está contido no nome da coluna
    if any(t_id in col for t_id in train_ids_str):
        train_cols.append(col)
    # Se não for treino, verifica se é teste
    elif any(t_id in col for t_id in test_ids_str):
        test_cols.append(col)
    else:
        # Se a coluna não deu match com nenhum dos dois, guardamos para investigar
        unmatched_cols.append(col)

# 4. Criar os DataFrames finais
df_psa_merged_train = df_psa_merged[train_cols].copy()
df_psa_merged_test = df_psa_merged[test_cols].copy()

# --- Verificações ---
print(f'Total original columns: {len(df_psa_merged.columns)}')
print(f'Train columns: {len(df_psa_merged_train.columns)}')
print(f'Test columns: {len(df_psa_merged_test.columns)}')

# Checar se perdemos alguma coluna no processo (a soma deve bater, lembrando que 'period(s)' conta nos dois)
# Total = Train + Test - 1 (por causa da coluna 'period(s)') + Unmatched
expected_total = len(train_cols) + len(test_cols) - 1 + len(unmatched_cols)
print(f'Math check (Expected = {len(df_psa_merged.columns)}, Calculated = {expected_total}): {"OK" if len(df_psa_merged.columns) == expected_total else "ERRO"}')

if unmatched_cols:
    print(f'\nAviso: {len(unmatched_cols)} colunas não encontraram correspondência com os IDs.')
    print(f'Exemplos de colunas sem match: {unmatched_cols[:5]}')

"""## Remove outliers"""

selected_atributes = ['magnitude',
             'calculated_epicentral_distance', 'depth', 'calculated_incidence_angle',
             'calculated_hypocentral_distance', 'peak_ground_acceleration', 'source_off_shore',
             'calculated_azimuth']

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import LocalOutlierFactor

# 1. Escalonamento correto (FIT apenas no treino para evitar vazamento de dados)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(train_set[selected_atributes])
X_test_scaled = scaler.transform(test_set[selected_atributes]) # Apenas transform!

# 2. Aplicar o LOF apenas no treino
clf = LocalOutlierFactor(contamination=0.001, n_neighbors=200)
# LOF retorna 1 para inliers (normais) e -1 para outliers
train_outliers_labels = clf.fit_predict(X_train_scaled)

print('outliers')
print(train_set[train_outliers_labels == -1]['station_earthquakeid'])

# 3. Criar o conjunto de treino limpo (mantendo apenas os inliers)
train_set_clean = train_set[train_outliers_labels == 1].copy()

print(f"Tamanho do treino original: {len(train_set)}")
print(f"Tamanho do treino sem outliers: {len(train_set_clean)}")
print(f"Foram removidos {len(train_set) - len(train_set_clean)} outliers do treino.")

# O seu test_set permanece com o mesmo número de linhas!

train_set = train_set_clean

"""## PSA preprocessing"""

df_psa_merged.shape

columns = df_psa_merged_train.columns
stations_train = []

for column in columns:
  if(column == 'period(s)'):
    continue
  station = column.split('-')[0]

  stations_train.append(station)


stations_train_set = set(stations_train)
print(stations_train_set)

stations_train_list = list(stations_train_set)
df_merge_spectral_coefs_mean = pd.DataFrame(columns=stations_train_list)
df_merge_spectral_mean = pd.DataFrame(columns=stations_train_list)
df_merge_horiz_spectral_mean = pd.DataFrame(columns=stations_train_list)
df_merge_vertical_spectral_mean = pd.DataFrame(columns=stations_train_list)

station_key_index=0
psa_samples_per_station = np.zeros(len(stations_train_set)) # total samples per stations

for station_key in stations_train_set:
  indexs_station_v = []
  indexs_station_ew = []
  indexs_station_ns = []
  v_signals = []
  ew_signals = []
  ns_signals = []

  for i in range(len(columns)):
    if columns[i] == 'period(s)':
      continue
    #actual_station_key = columns[i][:4]
    actual_station_key = columns[i].split("-")[0]
    orientation = columns[i].split("-")[-1]
    if actual_station_key == station_key:
      psa_samples_per_station[station_key_index] = psa_samples_per_station[station_key_index] + 1
      if orientation == 'V':
        indexs_station_v.append(i)
        # print(columns[i])
        # signals = df_psa_merged_train.iloc[:, i].values
        # if(signals)==0:
        #   print(f"id with signals zero: {i}")
        v_signals.append(df_psa_merged_train.iloc[:, i].values)

        if(min(v_signals[0])==0):
          print(actual_station_key)
          print(columns[i])

      elif orientation == 'EW':
        indexs_station_ew.append(i)
        ew_signals.append(df_psa_merged_train.iloc[:, i].values)
      elif orientation == 'NS':
        indexs_station_ns.append(i)
        ns_signals.append(df_psa_merged_train.iloc[:, i].values)
      else:
        print('unknown orientation')

  station_key_index +=1

  v_mean = np.mean(v_signals, axis=0)
  ew_mean = np.mean(ew_signals, axis=0)
  ns_mean = np.mean(ns_signals, axis=0)

  if(min(v_mean)==0):
    print(station_key)

  ew_v_spectral_coeficients = ew_mean / v_mean
  ns_v_spectral_coeficients = ns_mean / v_mean
  spectral_coefs_mean = np.mean(np.array([ew_v_spectral_coeficients, ns_v_spectral_coeficients]), axis=0)
  df_merge_spectral_coefs_mean[station_key]=spectral_coefs_mean

  spectral_means = np.mean(np.array([v_mean, ew_mean, ns_mean]), axis=0)
  df_merge_spectral_mean[station_key]=spectral_means

  h_spectral_means = np.mean(np.array([ew_mean, ns_mean]), axis=0)
  df_merge_horiz_spectral_mean[station_key]=h_spectral_means

  df_merge_vertical_spectral_mean[station_key]=v_mean

psa_samples_per_station

#Figure: a) Spectral Ratio, b) Three Axis Spectra c) Horizontal Spectral d) Vertical Spectra

fig, axs = plt.subplots(2, 2, figsize=(8,6))
axs[0,0].plot(df_psa_merged_train['period(s)'].values, df_merge_spectral_coefs_mean.values)
axs[0,0].set_ylabel('Dimensionless')
axs[0,0].set_title('(a)')

axs[0,1].plot(df_psa_merged_train['period(s)'].values, df_merge_spectral_mean.values)
axs[0,1].set_ylabel('cm/s$^2$')
axs[0,1].set_title('(b)')

axs[1, 0].plot(df_psa_merged_train['period(s)'].values, df_merge_horiz_spectral_mean.values)
axs[1, 0].set_xlabel('Period (s)')
axs[1, 0].set_ylabel('cm/s$^2$')
axs[1, 0].set_title('(c)')

axs[1, 1].plot(df_psa_merged_train['period(s)'].values, df_merge_vertical_spectral_mean.values)
axs[1, 1].set_xlabel('Period (s)')
axs[1, 1].set_ylabel('cm/s$^2$')
axs[1, 1].set_title('(d)')

plt.tight_layout()

plt.show()

"""Figure: a) Spectral Ratio, b) Three Axis Spectra c) Horizontal Spectral d) Vertical Spectra

### test set
"""

columns = df_psa_merged_test.columns
stations_train = []

for column in columns:
  if(column == 'period(s)'):
    continue
  station = column.split('-')[0]

  stations_train.append(station)


stations_test_set = set(stations_train)
print(stations_test_set)

stations_test_list = list(stations_test_set)
df_merge_spectral_coefs_mean_test = pd.DataFrame(columns=stations_test_list)
df_merge_spectral_mean_test = pd.DataFrame(columns=stations_test_list)
df_merge_horiz_spectral_mean_test = pd.DataFrame(columns=stations_test_list)
df_merge_vertical_spectral_mean_test = pd.DataFrame(columns=stations_test_list)

station_key_index=0
psa_samples_per_station = np.zeros(len(stations_test_list)) # total samples per stations

df_local = df_psa_merged_test

for station_key in stations_test_list:
  indexs_station_v = []
  indexs_station_ew = []
  indexs_station_ns = []
  v_signals = []
  ew_signals = []
  ns_signals = []

  for i in range(len(columns)):
    if columns[i] == 'period(s)':
      continue
    #actual_station_key = columns[i][:4]
    actual_station_key = columns[i].split("-")[0]
    orientation = columns[i].split("-")[-1]
    if actual_station_key == station_key:
      psa_samples_per_station[station_key_index] = psa_samples_per_station[station_key_index] + 1
      if orientation == 'V':
        indexs_station_v.append(i)

        v_signals.append(df_local.iloc[:, i].values)

        if(min(v_signals[0])==0):
          print(actual_station_key)
          print(columns[i])

      elif orientation == 'EW':
        indexs_station_ew.append(i)
        ew_signals.append(df_local.iloc[:, i].values)
      elif orientation == 'NS':
        indexs_station_ns.append(i)
        ns_signals.append(df_local.iloc[:, i].values)
      else:
        print('unknown orientation')

  station_key_index +=1

  v_mean = np.mean(v_signals, axis=0)
  ew_mean = np.mean(ew_signals, axis=0)
  ns_mean = np.mean(ns_signals, axis=0)

  if(min(v_mean)==0):
    print(station_key)

  ew_v_spectral_coeficients = ew_mean / v_mean
  ns_v_spectral_coeficients = ns_mean / v_mean
  spectral_coefs_mean = np.mean(np.array([ew_v_spectral_coeficients, ns_v_spectral_coeficients]), axis=0)
  df_merge_spectral_coefs_mean_test[station_key]=spectral_coefs_mean

  spectral_means = np.mean(np.array([v_mean, ew_mean, ns_mean]), axis=0)
  df_merge_spectral_mean_test[station_key]=spectral_means

  h_spectral_means = np.mean(np.array([ew_mean, ns_mean]), axis=0)
  df_merge_horiz_spectral_mean_test[station_key]=h_spectral_means

  df_merge_vertical_spectral_mean_test[station_key]=v_mean

"""## PSA Clustering"""

train_set.columns

"""### spectral coefs"""

# 1. Inicializa o MinMaxScaler
scaler = MinMaxScaler()

# 2. Aplica o scaler no DataFrame
Xscaled = scaler.fit_transform(df_merge_spectral_coefs_mean)

print(Xscaled)

# Recriando o DataFrame para manter índices e colunas originais
df_scaled = pd.DataFrame(
    Xscaled,
    index=df_merge_spectral_coefs_mean.index,
    columns=df_merge_spectral_coefs_mean.columns
)

df_scaled.describe()

df_scaled_t = df_scaled.T

scores = []
for i in range(2, 8):
  kmeans = KMeans(n_clusters=i, random_state=42, n_init=10).fit(df_scaled_t)
  scores.append(kmeans.inertia_)

plt.plot(range(2,8), scores)

fig, ax = plt.subplots(2, 2, figsize=(6,5))
for i in [2, 3, 4, 5]:
    '''
    Create KMeans instance for different number of clusters
    '''
    km = KMeans(n_clusters=i, init='k-means++', n_init=10, max_iter=300, random_state=42)
    q, mod = divmod(i, 2)
    '''
    Create SilhouetteVisualizer instance with KMeans instance
    Fit the visualizer
    '''
    visualizer = SilhouetteVisualizer(km, colors='yellowbrick', ax=ax[q-1][mod])
    visualizer.fit(df_scaled_t)

plt.tight_layout()
plt.show()

k=4
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
Xscaled = df_scaled_t.values
df_scaled_t['Cluster'] = kmeans.fit_predict(df_scaled_t)

labels_kmeans_spectral_coefs_mean = kmeans.labels_

fig, axs = plt.subplots(1, k, figsize=(9,3))
row_i=0
column_j=0

# For each label there is,
# plots every series with that label
for label in set(labels_kmeans_spectral_coefs_mean):
    cluster = []
    for i in range(len(labels_kmeans_spectral_coefs_mean)):
      if(labels_kmeans_spectral_coefs_mean[i]==label):
          axs[column_j].plot(Xscaled[i], c="gray", alpha=0.4)
          cluster.append(Xscaled[i])
    if len(cluster) > 0:
        axs[column_j].plot(np.average(np.vstack(cluster),axis=0),c="red")
    axs[column_j].set_title("Cluster "+str(label))
    column_j+=1


plt.tight_layout()
plt.show()

#clusters_kmeans_spectral_coefs_mean_dict = dict(zip(station_keys_set, labels_kmeans_spectral_coefs_mean))

clusters_kmeans_spectral_coefs_mean_dict = df_scaled_t['Cluster'].to_dict()
print(clusters_kmeans_spectral_coefs_mean_dict)

scaler_teste = MinMaxScaler()
test_set_scaled = scaler_teste.fit_transform(df_merge_spectral_coefs_mean_test)

df_test_set_scaled_t = pd.DataFrame(
    test_set_scaled,
    index=df_merge_spectral_coefs_mean_test.index,
    columns=df_merge_spectral_coefs_mean_test.columns
).T

df_test_set_scaled_t['Cluster'] = kmeans.predict(df_test_set_scaled_t)
clusters_kmeans_spectral_coefs_mean_dict_test = df_test_set_scaled_t['Cluster'].to_dict()

clusters_kmeans_spectral_coefs_mean_dict = {**clusters_kmeans_spectral_coefs_mean_dict, **clusters_kmeans_spectral_coefs_mean_dict_test}

len(clusters_kmeans_spectral_coefs_mean_dict)

"""### spectral mean"""

# 1. Inicializa o MinMaxScaler
scaler = MinMaxScaler()

# 2. Aplica o scaler no DataFrame
Xscaled = scaler.fit_transform(df_merge_spectral_mean)

print(Xscaled)

# Recriando o DataFrame para manter índices e colunas originais
df_scaled = pd.DataFrame(
    Xscaled,
    index=df_merge_spectral_mean.index,
    columns=df_merge_spectral_mean.columns
)

df_scaled_t = df_scaled.T

fig, ax = plt.subplots(2, 2, figsize=(7,5))
for i in [2, 3, 4, 5]:
    '''
    Create KMeans instance for different number of clusters
    '''
    km = KMeans(n_clusters=i, init='k-means++', n_init=10, max_iter=300, random_state=42)
    q, mod = divmod(i, 2)
    '''
    Create SilhouetteVisualizer instance with KMeans instance
    Fit the visualizer
    '''
    axe = ax[q-1][mod]
    visualizer = SilhouetteVisualizer(km, colors='yellowbrick', ax=axe)
    visualizer.fit(df_scaled_t)
    axe.set_xlim([-0.15, 0.7])

plt.tight_layout()
plt.show()

k=4
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
Xscaled = df_scaled_t.values
df_scaled_t['Cluster'] = kmeans.fit_predict(df_scaled_t)

labels_kmeans_spectral_mean = kmeans.labels_

fig, axs = plt.subplots(1, k, figsize=(9,3))
row_i=0
column_j=0

# For each label there is,
# plots every series with that label
for label in set(labels_kmeans_spectral_mean):
    cluster = []
    for i in range(len(labels_kmeans_spectral_mean)):
      if(labels_kmeans_spectral_mean[i]==label):
          axs[column_j].plot(Xscaled[i], c="gray", alpha=0.4)
          cluster.append(Xscaled[i])
    if len(cluster) > 0:
        axs[column_j].plot(np.average(np.vstack(cluster),axis=0),c="red")
    axs[column_j].set_title("Cluster "+str(label))
    column_j+=1


plt.tight_layout()
plt.show()

#clusters_kmeans_spectral_mean_dict = dict(zip(station_keys_set, labels_kmeans_spectral_mean))

clusters_kmeans_spectral_mean_dict = df_scaled_t['Cluster'].to_dict()
print(clusters_kmeans_spectral_mean_dict)

scaler_teste = MinMaxScaler()
test_set_scaled = scaler_teste.fit_transform(df_merge_spectral_mean_test)

df_test_set_scaled_t = pd.DataFrame(
    test_set_scaled,
    index=df_merge_spectral_mean_test.index,
    columns=df_merge_spectral_mean_test.columns
).T

df_test_set_scaled_t['Cluster'] = kmeans.predict(df_test_set_scaled_t)
clusters_kmeans_spectral_mean_dict_test = df_test_set_scaled_t['Cluster'].to_dict()

clusters_kmeans_spectral_mean_dict = {**clusters_kmeans_spectral_mean_dict, **clusters_kmeans_spectral_mean_dict_test}

len(clusters_kmeans_spectral_mean_dict)

"""### spectral horizontal mean"""

# 1. Inicializa o MinMaxScaler
scaler = MinMaxScaler()

# 2. Aplica o scaler no DataFrame
Xscaled = scaler.fit_transform(df_merge_horiz_spectral_mean)

print(Xscaled)

# Recriando o DataFrame para manter índices e colunas originais
df_scaled = pd.DataFrame(
    Xscaled,
    index=df_merge_horiz_spectral_mean.index,
    columns=df_merge_horiz_spectral_mean.columns
)

df_scaled_t = df_scaled.T

fig, ax = plt.subplots(2, 2, figsize=(10,6))
for i in [2, 3, 4, 5]:
    '''
    Create KMeans instance for different number of clusters
    '''
    km = KMeans(n_clusters=i, init='k-means++', n_init=10, max_iter=300, random_state=42)
    q, mod = divmod(i, 2)
    '''
    Create SilhouetteVisualizer instance with KMeans instance
    Fit the visualizer
    '''
    visualizer = SilhouetteVisualizer(km, colors='yellowbrick', ax=ax[q-1][mod])
    visualizer.fit(df_scaled_t)

k=4
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
Xscaled = df_scaled_t.values
df_scaled_t['Cluster'] = kmeans.fit_predict(df_scaled_t)

labels_kmeans_spectral_horiz_mean = kmeans.labels_

fig, axs = plt.subplots(1, k, figsize=(9,3))
row_i=0
column_j=0

# For each label there is,
# plots every series with that label
for label in set(labels_kmeans_spectral_horiz_mean):
    cluster = []
    for i in range(len(labels_kmeans_spectral_horiz_mean)):
      if(labels_kmeans_spectral_horiz_mean[i]==label):
          axs[column_j].plot(Xscaled[i], c="gray", alpha=0.4)
          cluster.append(Xscaled[i])
    if len(cluster) > 0:
        axs[column_j].plot(np.average(np.vstack(cluster),axis=0),c="red")
    axs[column_j].set_title("Cluster "+str(label))
    column_j+=1


plt.tight_layout()
plt.show()

#clusters_kmeans_spectral_horiz_mean_dict = dict(zip(station_keys_set, labels_kmeans_spectral_horiz_mean))

clusters_kmeans_spectral_horiz_mean_dict = df_scaled_t['Cluster'].to_dict()
print(clusters_kmeans_spectral_horiz_mean_dict)

scaler_teste = MinMaxScaler()
test_set_scaled = scaler_teste.fit_transform(df_merge_horiz_spectral_mean_test)

df_test_set_scaled_t = pd.DataFrame(
    test_set_scaled,
    index=df_merge_horiz_spectral_mean_test.index,
    columns=df_merge_horiz_spectral_mean_test.columns
).T

df_test_set_scaled_t['Cluster'] = kmeans.predict(df_test_set_scaled_t)
clusters_kmeans_spectral_horiz_mean_dict_test = df_test_set_scaled_t['Cluster'].to_dict()

clusters_kmeans_spectral_horiz_mean_dict = {**clusters_kmeans_spectral_horiz_mean_dict, **clusters_kmeans_spectral_horiz_mean_dict_test}

len(clusters_kmeans_spectral_horiz_mean_dict)

"""### spectral vertical mean"""

# 1. Inicializa o MinMaxScaler
scaler = MinMaxScaler()

# 2. Aplica o scaler no DataFrame
Xscaled = scaler.fit_transform(df_merge_vertical_spectral_mean)

print(Xscaled)

# Recriando o DataFrame para manter índices e colunas originais
df_scaled = pd.DataFrame(
    Xscaled,
    index=df_merge_vertical_spectral_mean.index,
    columns=df_merge_vertical_spectral_mean.columns
)

df_scaled_t = df_scaled.T

fig, ax = plt.subplots(2, 2, figsize=(10,6))
for i in [2, 3, 4, 5]:
    '''
    Create KMeans instance for different number of clusters
    '''
    km = KMeans(n_clusters=i, init='k-means++', n_init=10, max_iter=300, random_state=42)
    q, mod = divmod(i, 2)
    '''
    Create SilhouetteVisualizer instance with KMeans instance
    Fit the visualizer
    '''
    visualizer = SilhouetteVisualizer(km, colors='yellowbrick', ax=ax[q-1][mod])
    visualizer.fit(df_scaled_t)

k=4
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
Xscaled = df_scaled_t.values
df_scaled_t['Cluster'] = kmeans.fit_predict(df_scaled_t)

labels_kmeans_spectral_vert_mean = kmeans.labels_

fig, axs = plt.subplots(1, k, figsize=(9,3))
row_i=0
column_j=0

# For each label there is,
# plots every series with that label
for label in set(labels_kmeans_spectral_vert_mean):
    cluster = []
    for i in range(len(labels_kmeans_spectral_vert_mean)):
      if(labels_kmeans_spectral_vert_mean[i]==label):
          axs[column_j].plot(Xscaled[i], c="gray", alpha=0.4)
          cluster.append(Xscaled[i])
    if len(cluster) > 0:
        axs[column_j].plot(np.average(np.vstack(cluster),axis=0),c="red")
    axs[column_j].set_title("Cluster "+str(label))
    column_j+=1


plt.tight_layout()
plt.show()

#clusters_kmeans_spectral_vert_mean_dict = dict(zip(station_keys_set, labels_kmeans_spectral_vert_mean))

clusters_kmeans_spectral_vert_mean_dict = df_scaled_t['Cluster'].to_dict()
print(clusters_kmeans_spectral_vert_mean_dict)

scaler_teste = MinMaxScaler()
test_set_scaled = scaler_teste.fit_transform(df_merge_vertical_spectral_mean_test)

df_test_set_scaled_t = pd.DataFrame(
    test_set_scaled,
    index=df_merge_vertical_spectral_mean_test.index,
    columns=df_merge_vertical_spectral_mean_test.columns
).T

df_test_set_scaled_t['Cluster'] = kmeans.predict(df_test_set_scaled_t)
clusters_kmeans_spectral_vert_mean_dict_test = df_test_set_scaled_t['Cluster'].to_dict()

clusters_kmeans_spectral_vert_mean_dict = {**clusters_kmeans_spectral_vert_mean_dict, **clusters_kmeans_spectral_vert_mean_dict_test}

len(clusters_kmeans_spectral_vert_mean_dict)

"""## Add cluster column"""

train_set.reset_index(drop=True, inplace=True)

def add_clusters(df, clusters_dict, cluster_column_name):
  lost_stations = []
  df_com_clusters = df.copy()

  for index, row in df_com_clusters.iterrows():
    station_key = df_com_clusters['station_key'].iloc[index]
    try:
      df_com_clusters.at[index, cluster_column_name] = clusters_dict[station_key]
    except:
      lost_stations.append(station_key)
  return df_com_clusters, lost_stations

train_set_with_clusters, lost_stations = add_clusters(train_set, clusters_kmeans_spectral_coefs_mean_dict, 'clusters_spectral_coefs')
lost_stations

train_set_with_clusters, lost_stations = add_clusters(train_set_with_clusters, clusters_kmeans_spectral_mean_dict, 'clusters_spectral_means')
lost_stations

train_set_with_clusters, lost_stations = add_clusters(train_set_with_clusters, clusters_kmeans_spectral_horiz_mean_dict, 'clusters_spectral_horiz_means')
lost_stations

train_set_with_clusters, lost_stations = add_clusters(train_set_with_clusters, clusters_kmeans_spectral_vert_mean_dict, 'clusters_spectral_vert_means')
lost_stations

test_set.reset_index(drop=True, inplace=True)

test_set_with_clusters, lost_stations = add_clusters(test_set, clusters_kmeans_spectral_coefs_mean_dict, 'clusters_spectral_coefs')
lost_stations

test_set_with_clusters, lost_stations = add_clusters(test_set_with_clusters, clusters_kmeans_spectral_mean_dict, 'clusters_spectral_means')
lost_stations

test_set_with_clusters, lost_stations = add_clusters(test_set_with_clusters, clusters_kmeans_spectral_horiz_mean_dict, 'clusters_spectral_horiz_means')
lost_stations

test_set_with_clusters, lost_stations = add_clusters(test_set_with_clusters, clusters_kmeans_spectral_vert_mean_dict, 'clusters_spectral_vert_means')

train_set = train_set_with_clusters
test_set = test_set_with_clusters

"""### map visualization"""

df_com_clusters, lost_stations = add_clusters(df, clusters_kmeans_spectral_coefs_mean_dict, 'clusters_spectral_coefs')

df_com_clusters, lost_stations = add_clusters(df_com_clusters, clusters_kmeans_spectral_mean_dict, 'clusters_spectral_means')

df_com_clusters, lost_stations = add_clusters(df_com_clusters, clusters_kmeans_spectral_horiz_mean_dict, 'clusters_spectral_horiz_means')

df_com_clusters, lost_stations = add_clusters(df_com_clusters, clusters_kmeans_spectral_vert_mean_dict, 'clusters_spectral_vert_means')

train_set_with_clusters.clusters_spectral_means.value_counts()

#ax1 = map.plot(figsize=(8,6), alpha=0.5)

# Faça o plot
fig, ax1 = plt.subplots(figsize=(8, 6))

# Plote o contorno do México
world.plot(ax=ax1, edgecolor='black', facecolor='green', linewidth=1, zorder=1, alpha=0.5)

# Adicionar marcadores para cada localização
for lon, lat, name in locations:
    ax1.plot(lon, lat, 'ko', markersize=3)
    ax1.text(lon, lat, name, color='w', fontsize=8, ha='right', va='bottom')

g = sns.scatterplot(ax=ax1,
                data=df_com_clusters,
                x='station_longitude',
                y='station_latitude',
                #size='clusters_spectral_means',
                hue='clusters_spectral_means',
                #sizes=(20, 200),
                #marker=(8,1,0),
                s=50,
                zorder=2,
                palette=sns.color_palette('colorblind'))

#plt.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.legend(frameon=True, title='Station Cluster')

ax1.set(xlabel='Longitude', ylabel='Latitude')
plt.xlim([-106, -90])
plt.ylim([13, 22])

# Definir intervalos para os ticks
ax1.xaxis.set_major_locator(ticker.MultipleLocator(2))  # Intervalo de 2 graus
ax1.yaxis.set_major_locator(ticker.MultipleLocator(1))  # Intervalo de 1 grau

# Formatar os labels com o símbolo de grau
def longitude_formatter(x, p):
    return f'{x}°W'

def latitude_formatter(x, p):
    return f'{x}°N'

ax1.xaxis.set_major_formatter(ticker.FuncFormatter(longitude_formatter))
ax1.yaxis.set_major_formatter(ticker.FuncFormatter(latitude_formatter))

# Rotacionar os labels do eixo x para melhor legibilidade
plt.xticks(rotation=45)

# Ajustar o layout para evitar cortes
plt.tight_layout()


plt.show()

"""# Machine Learning Regression"""

X_train_dnn, X_valid_dnn, y_train_dnn, y_valid_dnn = train_test_split(train_set, train_set.peak_ground_acceleration, test_size=0.2, random_state=42) #for DNN

# num_attributes = ['magnitude',
#              'calculated_epicentral_distance', 'depth', 'calculated_incidence_angle',
#              'calculated_hypocentral_distance', 'calculated_azimuth', 'source_off_shore', 'log_incidence_angle']

num_attributes = ['magnitude',
             'calculated_epicentral_distance', 'depth', 'calculated_incidence_angle',
             'calculated_hypocentral_distance', 'source_off_shore', 'log_incidence_angle']

num_pipeline = Pipeline([
  ("standardize", StandardScaler()),
])

"""## hiperparameters tuning

clusters_spectral_means selected to hiperparameters tuning
"""

# selected_cluster_column = 'clusters_spectral_means'
# cat_attribs = [selected_cluster_column]


# cat_pipeline = make_pipeline(
#   SimpleImputer(strategy="most_frequent"),
#   OneHotEncoder(handle_unknown="ignore"))


# preprocessor = ColumnTransformer([
#   ("cat", cat_pipeline, cat_attribs),
#   ('num', num_pipeline, num_attributes)
#   ], remainder="drop")

preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_attributes)
    ], remainder="drop")

"""### Random Forest Grid Search"""

steps = [
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(random_state=42))
]

pipeline = Pipeline(steps)

param_grid = [
    {'model__n_estimators': [300, 500, 700, 900, 1200, 1500, 1800, 2100],
     'model__max_features': [0.3, 0.2, 0.1],
  }]


grid_search = GridSearchCV(pipeline, param_grid, cv=5,
                           scoring='neg_mean_squared_error',
                           return_train_score=False,
                           verbose=2)

if hiperparameters_tuning:
  grid_search.fit(train_set, train_set['peak_ground_acceleration'])

  print(grid_search.best_params_)
  print(np.sqrt(-grid_search.best_score_))
  best_grid = grid_search.best_estimator_
  pred = best_grid.predict(test_set)
  #rmse = mean_squared_error(test_set['peak_ground_acceleration'], pred, squared=False)
  #rmse = mean_squared_error(test_set['peak_ground_acceleration'], pred)
  rmse = root_mean_squared_error(test_set['peak_ground_acceleration'], pred)
  print(rmse)
  print(best_grid['model'].feature_importances_)

"""{'model__max_features': 0.3, 'model__n_estimators': 2100}

#### Optuna
"""

#hiperparameters_tuning = True

if hiperparameters_tuning:
    def objective(trial):
        param = {
            'n_estimators': trial.suggest_int('n_estimators', 100, 2000),
            'max_depth': trial.suggest_int('max_depth', 3, 30),
            'min_samples_split': trial.suggest_int('min_samples_split', 2, 20),
            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 20),
            'max_features': trial.suggest_float('max_features', 0.1, 1.0),
            'random_state': 42,
            'n_jobs': -1
        }

        X_train_processed = preprocessor.fit_transform(train_set)
        y_train = train_set['peak_ground_acceleration']

        # Instanciando o RandomForestRegressor
        reg = RandomForestRegressor(**param)

        # Validação cruzada
        kfold = KFold(n_splits=5, shuffle=True, random_state=42)
        score = cross_val_score(reg, X_train_processed, y_train,
                                cv=kfold,
                                scoring='neg_root_mean_squared_error').mean()

        return score

    # Criação e execução do estudo do Optuna
    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=300)

    print("Melhores hiperparâmetros: ", study.best_params)
    print("Melhor score (neg_mean_squared_error): ", study.best_value)

"""30/03/2026
Melhores hiperparâmetros:  {'n_estimators': 1168, 'max_depth': 29, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.20810931707493818}
Melhor score (neg_mean_squared_error):  -1391.0214336442918

### Neural network keras tuner
"""

def build_model(hp):
  n_hidden = hp.Int("n_hidden", min_value=2, max_value=11, default=2)
  n_neurons = hp.Int("n_neurons", min_value=100, max_value=1800)
  learning_rate = hp.Float("learning_rate", min_value=1e-4, max_value=1e-2,
                           sampling="log")
  optimizer = hp.Choice("optimizer", values=["adam", 'nesterov'])
  activation_function = hp.Choice("activation", values=["relu", "swish"])

  if optimizer == "sgd":
    optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate)
  elif optimizer == "nesterov":
    optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate, nesterov=True, momentum=0.9)
  elif optimizer == "adamw":
    optimizer = tf.keras.optimizers.AdamW(learning_rate=learning_rate)
  else:
    optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)

  model = tf.keras.Sequential()
  model.add(tf.keras.layers.Flatten())

  for _ in range(n_hidden):
    model.add(tf.keras.layers.Dense(n_neurons, activation=activation_function, kernel_initializer="he_normal"))
    model.add(tf.keras.layers.BatchNormalization())

  model.add(tf.keras.layers.Dense(1))
  model.compile(loss="huber",  #loss="mse",
                optimizer=optimizer,
                metrics=["root_mean_squared_error"])
  return model

tf_x_train = preprocessor.fit_transform(X_train)
tf_x_valid = preprocessor.transform(X_valid)

tuner = kt.Hyperband(build_model,
                     objective=kt.Objective("val_root_mean_squared_error", direction="min"),
                     max_epochs=50,
                     factor=3,
                     directory='my_dir',
                     project_name='keras_tuner',
                     seed=42,
                     overwrite=True)
stop_early = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10)

#hiperparameters_tuning = True

if hiperparameters_tuning:
  tuner.search(tf_x_train, y_train, validation_data=(tf_x_valid, y_valid), callbacks=[stop_early], verbose=2)
  best_trial = tuner.oracle.get_best_trials(num_trials=1)[0]
  print(best_trial.summary())

"""Trial 90 Complete [00h 03m 53s]
val_root_mean_squared_error: 37.14332580566406

Best val_root_mean_squared_error So Far: 36.56245803833008
Total elapsed time: 01h 03m 57s
Trial 0088 summary
Hyperparameters:
n_hidden: 3
n_neurons: 419
learning_rate: 0.0005656677780014923
optimizer: nesterov
activation: swish
tuner/epochs: 50
tuner/initial_epoch: 0
tuner/bracket: 0
tuner/round: 0
Score: 36.56245803833008
None
"""



"""### XGboost"""

#hiperparameters_tuning = True

if hiperparameters_tuning:
  xgb_pipeline = Pipeline(steps=[
      ('preprocessor', preprocessor),
      ('regressor', xgb.XGBRegressor(random_state=42))
  ])


  param_grid = {
      'regressor__n_estimators': range(100, 1001, 2100), #[100, 300, 600, 900],
      'regressor__max_depth': range(4, 8, 1), #[4, 5, 6, 7],
      'regressor__subsample': [0.6, 0.7, 0.8, 0.9, 1.0],
      'regressor__colsample_bytree': [0.6, 0.7, 0.8, 0.9, 1.0],
      #'regressor__min_child_weight': range(0, 4, 1),
      #'regressor__gamma': range(0, 4, 1),
      #'regressor__reg_alpha' :  range(0, 20, 100), #hp.quniform('reg_alpha', 40,180,1),
      #'regressor__reg_lambda' : range(0, 20, 100), #hp.uniform('reg_lambda', 0,1),
  }


  kfold = KFold(n_splits=5, shuffle=True, random_state=42)

  grid_search = GridSearchCV(
      estimator=xgb_pipeline,
      param_grid=param_grid,
      #n_iter=100,
      scoring='neg_mean_squared_error',
      #n_jobs=-1,
      n_jobs=1,
      cv=kfold,
      verbose=10,
      #random_state=42
  )

  grid_search.fit(train_set, train_set['peak_ground_acceleration'])


  print("\n Best hiperparameters:")
  print(grid_search.best_params_)

  print("\nBest score (neg_mean_squared_error):")
  print(grid_search.best_score_)

  best_model = grid_search.best_estimator_

""" Best hiperparameters:
{'regressor__colsample_bytree': 1.0, 'regressor__max_depth': 4, 'regressor__n_estimators': 100, 'regressor__subsample': 0.9}

Best score (neg_mean_squared_error):
-1443.0433465419035
"""



"""#### Optuna"""

# hiperparameters_tuning = True

import numpy as np
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import optuna

# Assumindo que o seu 'train_set' e 'preprocessor' já estão definidos anteriormente

if hiperparameters_tuning:
    def objective(trial):
        param = {
            'objective': 'reg:squarederror',
            'n_estimators': trial.suggest_int('n_estimators', 100, 2100),
            'learning_rate': trial.suggest_float('learning_rate',  1e-4, 0.3, log=True),
            'max_depth': trial.suggest_int('max_depth', 3, 30),
            'subsample': trial.suggest_float('subsample', 0.1, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.1, 1.0),
            'min_child_weight': trial.suggest_int('min_child_weight', 0, 25),
            'gamma': trial.suggest_float('gamma', 1e-8, 5, log=True),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-2, 1e2, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-2, 1e2, log=True),
            'random_state': 42,
            'n_jobs': -1,
            # Adicionamos o early stopping diretamente nos parâmetros do estimador
            'early_stopping_rounds': 50
        }

        # 1. Separar as features (X), o alvo (y) e os grupos (IDs)
        X = train_set.drop(columns=['peak_ground_acceleration'])
        y = train_set['peak_ground_acceleration']
        groups = train_set['earthquake_id']

        # 2. Configurar o GroupKFold com 5 splits (melhor para evitar overfit)
        gkf = GroupKFold(n_splits=5)

        cv_scores = []

        # 3. Ciclo manual de Validação Cruzada
        for train_idx, val_idx in gkf.split(X, y, groups=groups):

            # Separar os dados desta iteração (fold)
            X_train_fold = X.iloc[train_idx]
            y_train_fold = y.iloc[train_idx]

            X_val_fold = X.iloc[val_idx]
            y_val_fold = y.iloc[val_idx]

            # 4. Aplicar o preprocessador (evitando data leakage)
            # O FIT acontece APENAS nos dados de treino deste fold
            X_train_processed = preprocessor.fit_transform(X_train_fold)
            # O transform é aplicado nos dados de validação
            X_val_processed = preprocessor.transform(X_val_fold)

            # 5. Inicializar o modelo XGBoost
            model = xgb.XGBRegressor(**param)

            # 6. Treinar o modelo passando o eval_set para o early stopping atuar
            model.fit(
                X_train_processed,
                y_train_fold,
                eval_set=[(X_val_processed, y_val_fold)],
                verbose=False # Coloque True se quiser ver o log de cada árvore a ser treinada
            )

            # 7. Obter a melhor pontuação alcançada antes de parar
            # Como o objective é reg:squarederror, a métrica interna padrão é o RMSE
            # O XGBoost guarda o melhor RMSE no atributo best_score
            best_rmse = model.best_score

            # O Optuna está configurado para 'maximize', por isso guardamos o valor negativo
            cv_scores.append(-best_rmse)

        # Retornamos a média do RMSE negativo através dos 5 folds
        return np.mean(cv_scores)

    # Criação do estudo no Optuna
    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=500)

    print("Melhores hiperparâmetros: ", study.best_params)
    print("Melhor pontuação (neg_root_mean_squared_error): ", study.best_value)

from sklearn.model_selection import GroupKFold, cross_val_score
from sklearn.pipeline import Pipeline
import xgboost as xgb
import optuna

if hiperparameters_tuning:
    def objective(trial):
        param = {
            'objective': 'reg:squarederror',
            'n_estimators': trial.suggest_int('n_estimators', 100, 2100),
            'learning_rate': trial.suggest_float('learning_rate',  1e-4, 0.3, log=True),
            'max_depth': trial.suggest_int('max_depth', 3, 30),
            'subsample': trial.suggest_float('subsample', 0.1, 1.0),
            'colsample_bytree': trial.suggest_float('colsample_bytree', 0.1, 1.0),
            'min_child_weight': trial.suggest_int('min_child_weight', 0, 25),
            'gamma': trial.suggest_float('gamma', 1e-8, 5, log=True),
            'reg_alpha': trial.suggest_float('reg_alpha', 1e-2, 1e2, log=True),
            'reg_lambda': trial.suggest_float('reg_lambda', 1e-2, 1e2, log=True),
            'random_state': 42,
            'n_jobs': -1
        }

        # 1. Separar as features (X), o alvo (y) e os grupos (IDs)
        # IMPORTANTE: Remova a coluna alvo do seu X_train
        X_train = train_set.drop(columns=['peak_ground_acceleration'])
        y_train = train_set['peak_ground_acceleration']
        groups = train_set['earthquake_id'] # A variável que define os grupos

        # 2. Criar um Pipeline (Garante que o fit do preprocessor ocorra SÓ nos folds de treino)
        reg = xgb.XGBRegressor(**param)
        pipeline = Pipeline(steps=[
            ('preprocessor', preprocessor),
            ('model', reg)
        ])

        # 3. Usar o GroupKFold
        # O GroupKFold não tem shuffle, ele simplesmente agrupa pelos IDs que você passar
        gkf = GroupKFold(n_splits=5)

        # 4. Rodar o cross_val_score passando o 'groups'
        score = cross_val_score(
            pipeline,
            X_train,
            y_train,
            cv=gkf,
            groups=groups, # Passando a lista de IDs para o split respeitá-los
            scoring='neg_root_mean_squared_error'
        ).mean()

        return score

    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=300)

    print("Best hyperparameters: ", study.best_params)
    print("Best score (neg_root_mean_squared_error): ", study.best_value)

"""Best hyperparameters:  {'n_estimators': 359, 'learning_rate': 0.03165784068962444, 'max_depth': 15, 'subsample': 0.1681879099636086, 'colsample_bytree': 0.7677353745221257, 'min_child_weight': 5, 'gamma': 1.8056645572212065e-06, 'reg_alpha': 1.9813104483797868, 'reg_lambda': 0.815507095882078}
Best score (neg_root_mean_squared_error):  -42.88155285514233
"""

if hiperparameters_tuning:
  def objective(trial):
    param = {
        'objective': 'reg:squarederror',
        'n_estimators': trial.suggest_int('n_estimators', 100, 2100),
        'learning_rate': trial.suggest_float('learning_rate',  1e-4, 0.3, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 30),
        'subsample': trial.suggest_float('subsample', 0.1, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.1, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 0, 25),
        'gamma': trial.suggest_float('gamma', 1e-8, 5, log=True),
        #'reg_alpha': trial.suggest_loguniform('reg_alpha', 1e-2, 1e2),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-2, 1e2, log=True),
        #'reg_lambda': trial.suggest_loguniform('reg_lambda', 1e-2, 1e2),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-2, 1e2, log=True),
        'random_state': 42,
        'n_jobs': -1
    }

    X_train_processed = preprocessor.fit_transform(train_set)
    y_train = train_set['peak_ground_acceleration']

    reg = xgb.XGBRegressor(**param)

    kfold = KFold(n_splits=3, shuffle=True, random_state=42)
    score = cross_val_score(reg, X_train_processed, y_train,
                            cv=kfold, scoring='neg_root_mean_squared_error').mean()

    return score


  study = optuna.create_study(direction='maximize')
  study.optimize(objective, n_trials=300)


  print("Best hiperparameters: ", study.best_params)
  print("Best score (neg_mean_squared_error): ", study.best_value)

"""30/03/2026
sem cluster
Best hiperparameters:  {'n_estimators': 1253, 'learning_rate': 0.009965726442034912, 'max_depth': 4, 'subsample': 0.8516909323324913, 'colsample_bytree': 0.49871310674941255, 'min_child_weight': 5, 'gamma': 3.6079684277444165e-06, 'reg_alpha': 19.298149002050515, 'reg_lambda': 0.025504335023581362}
Best score (neg_mean_squared_error):  -37.79636829811717

30/03/2026
Best hiperparameters:  {'n_estimators': 1903, 'learning_rate': 0.056824734682256905, 'max_depth': 11, 'subsample': 0.8574189245288927, 'colsample_bytree': 0.9488507780195735, 'min_child_weight': 11, 'gamma': 0.0006432941634246851, 'reg_alpha': 0.6784169742640414, 'reg_lambda': 72.70513574205368}
Best score (neg_mean_squared_error):  -1341.1315524127128

Best hiperparameters:  {'n_estimators': 837, 'learning_rate': 0.10092041078155438, 'max_depth': 24, 'subsample': 0.5049439324882802, 'colsample_bytree': 0.6592161178492533, 'min_child_weight': 6, 'gamma': 0.5847096182712899, 'reg_alpha': 3.251978029903381, 'reg_lambda': 84.12224324374611}
Best score (neg_mean_squared_error):  -1335.0159946735787

## Traning experiments
"""

train_set.shape

test_set.shape

# num_attributes = ['magnitude',
#              'calculated_epicentral_distance', 'depth', 'calculated_incidence_angle',
#              'calculated_hypocentral_distance', 'calculated_azimuth', 'source_off_shore', 'log_incidence_angle']

# num_pipeline = Pipeline([
#   ("standardize", StandardScaler()),
# ])

preprocessor = ColumnTransformer([
    ('num', num_pipeline, num_attributes)
    ], remainder="drop")

experiments = {}
trained_pipelines = {}

# RF_max_features=0.1
# RF_n_estimators= 900
# #RF_max_depth=
# #RF_min_samples_split
# #RF_min_samples_leaf
# RF_oob_score=False
# RF_warm_start=False

# RF_max_features=0.8295181197004419
# RF_n_estimators= 589
# RF_max_depth= 23
# RF_min_samples_split = 2
# RF_min_samples_leaf = 3
# RF_oob_score=False
# RF_warm_start=False


# RF_n_estimators= 1571
# RF_max_depth= 14
# RF_min_samples_split = 9
# RF_min_samples_leaf = 4
# RF_max_features=0.6304629822885958
# RF_oob_score=False
# RF_warm_start=False

#{'model__max_features': 0.3, 'model__n_estimators': 2100}
RF_n_estimators= 2100
RF_max_depth= 14
RF_min_samples_split = 9
RF_min_samples_leaf = 4
RF_max_features=0.3
RF_oob_score=False
RF_warm_start=False


# nn_neurons = 1583
# nn_hidden_layers = 5
# nn_activation = "swish"
# nn_learning_rate = 0.0006601146406744397

# Best val_root_mean_squared_error So Far: 36.56245803833008 Total elapsed time: 01h 03m 57s
# Trial 0088 summary Hyperparameters: n_hidden: 3 n_neurons: 419 learning_rate: 0.0005656677780014923
# optimizer: nesterov activation: swish tuner/epochs: 50 tuner/initial_epoch: 0 tuner/bracket: 0 tuner/round: 0 Score: 36.56245803833008 None
nn_neurons = 419
nn_hidden_layers = 3
nn_activation = "swish"
nn_learning_rate = 0.0005656677780014923


elasticnet_alpha=0.1
elasticnet_l1_ratio=0.5
elasticnet_max_iter=100000

polynomial_include_bias=True

nn_optimizer = keras.optimizers.SGD(learning_rate=nn_learning_rate, nesterov=True, momentum=0.9)


# xbg_colsample_bytree= 0.8950712208863197
# xbg_max_depth = 7
# xbg_n_estimators = 358
# xbg_subsample = 0.6287944976282687
# xbg_gamma = 2.8845334342509843
# xbg_min_child_weight = 2
# xbg_learning_rate = 0.01349849929832932
# xbg_reg_alpha = 0.840678380595821
# xbg_reg_lambda = 3.9477129819761734


# xbg_n_estimators = 215
# xbg_learning_rate = 0.04801837809067573
# xbg_max_depth = 27
# xbg_subsample = 0.3666717398618287
# xbg_colsample_bytree=  0.8109332690402515
# xbg_min_child_weight = 11
# xbg_gamma = 3.9606653932439215
# xbg_reg_alpha = 0.01466128333556409
# xbg_reg_lambda = 0.4516642359041898


# xbg_n_estimators = 261
# xbg_learning_rate = 0.039013930308612235
# xbg_max_depth = 7
# xbg_subsample = 0.3780800417902329
# xbg_colsample_bytree=  0.8326213820774643
# xbg_min_child_weight = 12
# xbg_gamma = 3.8948880142909856
# xbg_reg_alpha = 0.05162348742850506
# xbg_reg_lambda = 0.5677206268714267


# 30/03/2026 Best hiperparameters: {'n_estimators': 1903, 'learning_rate': 0.056824734682256905, 'max_depth': 11,
# 'subsample': 0.8574189245288927, 'colsample_bytree': 0.9488507780195735, 'min_child_weight': 11, 'gamma': 0.0006432941634246851,
# 'reg_alpha': 0.6784169742640414, 'reg_lambda': 72.70513574205368} Best score (neg_mean_squared_error): -1341.1315524127128

# xbg_n_estimators = 1903
# xbg_learning_rate = 0.056824734682256905
# xbg_max_depth = 11
# xbg_subsample = 0.8574189245288927
# xbg_colsample_bytree=  0.9488507780195735
# xbg_min_child_weight = 11
# xbg_gamma = 0.0006432941634246851
# xbg_reg_alpha = 3.6784169742640414
# xbg_reg_lambda = 72.70513574205368

# 30/03/2026 sem cluster Best hiperparameters: {'n_estimators': 1253, 'learning_rate': 0.009965726442034912, 'max_depth': 4,
# 'subsample': 0.8516909323324913, 'colsample_bytree': 0.49871310674941255, 'min_child_weight': 5, 'gamma': 3.6079684277444165e-06,
# 'reg_alpha': 19.298149002050515, 'reg_lambda': 0.025504335023581362} Best score (neg_mean_squared_error): -37.79636829811717
# xbg_n_estimators = 1253
# xbg_learning_rate = 0.009965726442034912
# xbg_max_depth = 4
# xbg_subsample = 0.8516909323324913
# xbg_colsample_bytree=  0.49871310674941255
# xbg_min_child_weight = 5
# xbg_gamma = 3.6079684277444165e-06
# xbg_reg_alpha = 19.298149002050515
# xbg_reg_lambda = 0.025504335023581362



# 30/03/2026 sem cluster kfold eventos
# Best hyperparameters:  {'n_estimators': 359, 'learning_rate': 0.03165784068962444, 'max_depth': 15, 'subsample': 0.1681879099636086,
# 'colsample_bytree': 0.7677353745221257, 'min_child_weight': 5, 'gamma': 1.8056645572212065e-06, 'reg_alpha': 1.9813104483797868, 'reg_lambda': 0.815507095882078}
# Best score (neg_root_mean_squared_error):  -42.88155285514233
# xbg_n_estimators = 359
# xbg_learning_rate = 0.03165784068962444
# xbg_max_depth = 15
# xbg_subsample = 0.1681879099636086
# xbg_colsample_bytree=  0.7677353745221257
# xbg_min_child_weight = 5
# xbg_gamma = 1.8056645572212065e-06
# xbg_reg_alpha = 1.9813104483797868
# xbg_reg_lambda = 0.815507095882078

# 30/03/2026 sem cluster, kfold eventos, sem azimuth
# Best hyperparameters:  {'n_estimators': 1158, 'learning_rate': 0.04168469311210112, 'max_depth': 3, 'subsample': 0.414713951345649, 'colsample_bytree': 0.3121922960499171,
# 'min_child_weight': 11, 'gamma': 0.2759047889053318, 'reg_alpha': 15.285025433862955, 'reg_lambda': 0.3318437888595277}
# Best score (neg_root_mean_squared_error):  -42.44569878457055
# xbg_n_estimators = 1158
# xbg_learning_rate = 0.04168469311210112
# xbg_max_depth = 3
# xbg_subsample = 0.414713951345649
# xbg_colsample_bytree=  0.3121922960499171
# xbg_min_child_weight = 11
# xbg_gamma = 0.2759047889053318
# xbg_reg_alpha = 15.285025433862955
# xbg_reg_lambda = 0.3318437888595277

# 30/03/2026 sem cluster, kfold eventos, sem azimuth, 500 trials
# Melhores hiperparâmetros:  {'n_estimators': 1734, 'learning_rate': 0.2543527611706547, 'max_depth': 18, 'subsample': 0.5809548106071651, 'colsample_bytree': 0.8882288814017651,
# 'min_child_weight': 1, 'gamma': 8.804203083872113e-07, 'reg_alpha': 0.272597395385441, 'reg_lambda': 0.10188365398056981}
# Melhor pontuação (neg_root_mean_squared_error):  -39.52945624526649
xbg_n_estimators = 1734
xbg_learning_rate = 0.2543527611706547
xbg_max_depth = 18
xbg_subsample = 0.5809548106071651
xbg_colsample_bytree=  0.8882288814017651
xbg_min_child_weight = 1
xbg_gamma = 8.804203083872113e-07
xbg_reg_alpha = 0.272597395385441
xbg_reg_lambda = 0.10188365398056981

def model_experiment(train_set, test_set, pipeline, experiments_dict, experiment_name):

  pipeline.fit(train_set, train_set['peak_ground_acceleration'])
  train_predictions = pipeline.predict(train_set)
  train_rmse = root_mean_squared_error(train_set['peak_ground_acceleration'], train_predictions)
  print(f"train rmse: {train_rmse}")

  predictions = pipeline.predict(test_set)
  #test_rmse = mean_squared_error(test_set['peak_ground_acceleration'], predictions, squared=False)
  test_rmse = root_mean_squared_error(test_set['peak_ground_acceleration'], predictions)
  print(f"test rmse: {test_rmse}")
  r2 = r2_score(test_set['peak_ground_acceleration'], predictions)

  confidence = 0.95
  squared_errors = (predictions - test_set['peak_ground_acceleration']) ** 2
  conf_interval = np.sqrt(stats.t.interval(confidence, len(squared_errors) - 1,
                           loc=squared_errors.mean(),
                           scale=stats.sem(squared_errors)))
  conf_range = conf_interval[1] - conf_interval[0]

  experiments_dict[experiment_name] = [test_rmse, r2, conf_interval[0], conf_interval[1]]

  return test_rmse, r2, pipeline, experiments_dict

"""### without clusters"""

if not load_trained_models:
  steps = [
      ('preprocessor', preprocessor),
      ('model', LinearRegression())
  ]

  pipeline = Pipeline(steps)

  model_name = 'Linear Regression'

  test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)

  trained_pipelines[model_name] = pipeline


  steps = [
      ('preprocessor', preprocessor),
      ('poly', PolynomialFeatures(degree=2, include_bias=polynomial_include_bias)),
      ('model', LinearRegression())
  ]

  pipeline = Pipeline(steps)

  model_name = 'Polynomial Regression'
  test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)

  trained_pipelines[model_name] = pipeline

  steps = [
      ('preprocessor', preprocessor),
      ('poly', PolynomialFeatures(degree=2, include_bias=polynomial_include_bias)),
      ('model', ElasticNet(alpha=elasticnet_alpha, l1_ratio=elasticnet_l1_ratio, max_iter=elasticnet_max_iter))
  ]

  pipeline = Pipeline(steps)

  model_name = 'Polynomial ElasticNet'
  test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)

  trained_pipelines[model_name] = pipeline


  steps = [
      ('preprocessor', preprocessor),
      ('model', RandomForestRegressor(max_features=RF_max_features,
                                      n_estimators=RF_n_estimators,
                                      max_depth=RF_max_depth,
                                      min_samples_split=RF_min_samples_split,
                                      min_samples_leaf=RF_min_samples_leaf,
                                      oob_score=RF_oob_score,
                                      warm_start=RF_warm_start,
                                      random_state=42))
  ]


  pipeline = Pipeline(steps)

  model_name = 'Random Forest'
  test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)

  trained_pipelines[model_name] =pipeline

if not load_trained_models:
  #tf.keras.backend.clear_session()

  model = tf.keras.Sequential()

  for _ in range(nn_hidden_layers):
      model.add(tf.keras.layers.Dense(nn_neurons, activation=nn_activation, kernel_initializer="he_normal"))
      model.add(tf.keras.layers.BatchNormalization())

  model.add(tf.keras.layers.Dense(1))

  rmse_metric = tf.keras.metrics.RootMeanSquaredError(name='rmse')
  nn_optimizer = keras.optimizers.SGD(learning_rate=nn_learning_rate, nesterov=True, momentum=0.9)
  model.compile(loss="huber",
                optimizer=nn_optimizer,
                metrics=[
                    rmse_metric
                    ])

if not load_trained_models:

  es = EarlyStopping(monitor='val_rmse',
                      mode='min',
                      verbose=1,
                      patience=10,
                      restore_best_weights=True
                      )


  tf_x_train = preprocessor.fit_transform(X_train_dnn)
  tf_x_valid = preprocessor.transform(X_valid_dnn)

  history = model.fit(tf_x_train, y_train_dnn,
                      epochs=100,
                      callbacks=[es],
                      validation_data=(tf_x_valid, y_valid_dnn),
                      verbose=1)


  tf_test = preprocessor.transform(test_set)
  predictions = model.predict(tf_test)

  #test_rmse = mean_squared_error(test_set['peak_ground_acceleration'], predictions, squared=False)
  test_rmse = root_mean_squared_error(test_set['peak_ground_acceleration'], predictions)
  r2 = r2_score(test_set['peak_ground_acceleration'], predictions)

  confidence = 0.95
  squared_errors = (predictions[:, 0] - test_set['peak_ground_acceleration']) ** 2
  conf_interval = np.sqrt(stats.t.interval(confidence, len(squared_errors) - 1,
                            loc=squared_errors.mean(),
                            scale=stats.sem(squared_errors)))
  conf_range = conf_interval[1] - conf_interval[0]

  model_name = 'Deep Neural Network'
  experiments[model_name] = [test_rmse, r2, conf_interval[0], conf_interval[1]]

  steps = [
      ('preprocessor', preprocessor),
      ('model', model)
    ]

  pipeline = Pipeline(steps)
  trained_pipelines[model_name] =pipeline

  pd.DataFrame(history.history).plot(
      figsize=(8, 5), grid=True, xlabel="Epoch",
      style=["r--", "r--.", "b-", "b-*"])
  plt.show()

# Add XGBoost model to experiments
model_name = 'XGBoost'
print(model_name)

steps = [
    ('preprocessor', preprocessor),
    ('model', xgb.XGBRegressor(objective='reg:squarederror',
                               colsample_bytree=xbg_colsample_bytree,
                               learning_rate=xbg_learning_rate,
                               max_depth=xbg_max_depth,
                               n_estimators=xbg_n_estimators,
                               subsample=xbg_subsample,
                               gamma = xbg_gamma,
                               min_child_weight = xbg_min_child_weight,
                               reg_alpha = xbg_reg_alpha,
                               reg_lambda = xbg_reg_lambda,
                               random_state=42)) # Use reg:squarederror for regression
]


pipeline = Pipeline(steps)

test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)
trained_pipelines[model_name] = pipeline

trained_pipelines[model_name]

# df_experiments = pd.DataFrame(experiments.values())
# df_experiments['Description'] = experiments.keys()
# df_experiments.columns = ['rmse', 'r2', 'CI Lower Bound','CI Upper Bound' ,'Description']
# df_experiments = df_experiments[['Description', 'rmse', 'r2', 'CI Lower Bound','CI Upper Bound' ]]
# df_experiments.sort_values(by='rmse')

"""### With clusters"""

cluster_columns = ['clusters_spectral_coefs', 'clusters_spectral_means', 'clusters_spectral_horiz_means', 'clusters_spectral_vert_means']

history_dnn = {}

def criar_modelo_dnn(nn_hidden_layers, nn_neurons, nn_activation, nn_optimizer):
    model = Sequential()
    for _ in range(nn_hidden_layers):
        model.add(Dense(nn_neurons, activation=nn_activation, kernel_initializer="he_normal"))
        model.add(BatchNormalization())
    model.add(Dense(1))

    rmse_metric = tf.keras.metrics.RootMeanSquaredError(name='rmse')

    model.compile(loss="huber",
                  optimizer=nn_optimizer,
                  metrics=[rmse_metric])

    return model

cat_pipeline = make_pipeline(
    # SimpleImputer(strategy="most_frequent"),
    OneHotEncoder(handle_unknown="ignore")
)

if not load_trained_models:
  for selected_cluster_column in cluster_columns:
    print(selected_cluster_column)

    cat_attribs = [selected_cluster_column]

    preprocessor_with_psa_cluster = ColumnTransformer([
      ("cat", cat_pipeline, cat_attribs),
      ('num', num_pipeline, num_attributes)
      ], remainder="drop")


    model_name = f'Linear Regression with PSA {selected_cluster_column}'
    print(model_name)
    steps = [
      ('preprocessor', preprocessor_with_psa_cluster),
      ('model', LinearRegression())
    ]

    pipeline = Pipeline(steps)

    test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)
    trained_pipelines[model_name] = pipeline


    model_name = f'Polynomial Regression with PSA {selected_cluster_column}'
    print(model_name)

    steps = [
        ('preprocessor', preprocessor_with_psa_cluster),
        ('poly', PolynomialFeatures(degree=2, include_bias=polynomial_include_bias)),
        ('model', LinearRegression())
    ]

    pipeline = Pipeline(steps)

    test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)
    trained_pipelines[model_name] = pipeline


    model_name = f'Polynomial ElasticNet with PSA {selected_cluster_column}'
    print(model_name)

    steps = [
      ('preprocessor', preprocessor_with_psa_cluster),
      ('poly', PolynomialFeatures(degree=2, include_bias=polynomial_include_bias)),
      ('model', ElasticNet(alpha=elasticnet_alpha, l1_ratio=elasticnet_l1_ratio, max_iter=elasticnet_max_iter))
    ]

    pipeline = Pipeline(steps)
    test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)

    trained_pipelines[model_name] = pipeline


    model_name = f'Random Forest with PSA {selected_cluster_column}'
    print(model_name)

    steps = [
      ('preprocessor', preprocessor_with_psa_cluster),
      ('model', RandomForestRegressor(max_features=RF_max_features,
                                      n_estimators=RF_n_estimators,
                                      max_depth=RF_max_depth,
                                      min_samples_split=RF_min_samples_split,
                                      min_samples_leaf=RF_min_samples_leaf,
                                      oob_score=RF_oob_score,
                                      warm_start=RF_warm_start,
                                      random_state=42))
    ]

    pipeline = Pipeline(steps)
    test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)
    trained_pipelines[model_name] = pipeline


    # model_name = f'Deep Neural Network with PSA {selected_cluster_column}'
    # print(model_name)

    # tf.keras.backend.clear_session()

    # nn_optimizer = keras.optimizers.SGD(learning_rate=nn_learning_rate, nesterov=True, momentum=0.9)
    # model = criar_modelo_dnn(nn_hidden_layers, nn_neurons, nn_activation, nn_optimizer)

    # es = EarlyStopping(monitor='val_rmse',
    #                     mode='min',
    #                     verbose=1,
    #                     patience=10,
    #                     restore_best_weights=True
    #                     )

    # tf_x_train = preprocessor_with_psa_cluster.fit_transform(X_train)
    # tf_x_valid = preprocessor_with_psa_cluster.transform(X_valid)

    # #tf.config.run_functions_eagerly(True)
    # tf.data.experimental.enable_debug_mode()
    # history = model.fit(tf_x_train, y_train,
    #                     epochs=50, callbacks=[es],
    #                     validation_data=(tf_x_valid, y_valid))
    # history_dnn[model_name] = history


    # steps = [
    #   ('preprocessor', preprocessor_with_psa_cluster),
    #   ('model', model)
    # ]
    # pipeline = Pipeline(steps)

    # predictions = pipeline.predict(test_set)
    # #test_rmse = mean_squared_error(test_set['peak_ground_acceleration'], predictions, squared=False)
    # test_rmse = root_mean_squared_error(test_set['peak_ground_acceleration'], predictions)
    # r2 = r2_score(test_set['peak_ground_acceleration'], predictions)

    # confidence = 0.95
    # squared_errors = (predictions[:, 0] - test_set['peak_ground_acceleration']) ** 2
    # conf_interval = np.sqrt(stats.t.interval(confidence, len(squared_errors) - 1,
    #                           loc=squared_errors.mean(),
    #                           scale=stats.sem(squared_errors)))
    # conf_range = conf_interval[1] - conf_interval[0]


    # experiments[model_name] = [test_rmse, r2, conf_interval[0], conf_interval[1]]

    # trained_pipelines[model_name] = pipeline

cat_pipeline = make_pipeline(
    SimpleImputer(strategy="most_frequent"),
    OneHotEncoder(handle_unknown="ignore"))


if not load_trained_models:
  for selected_cluster_column in cluster_columns:
    print(selected_cluster_column)

    cat_attribs = [selected_cluster_column]

    preprocessor_with_psa_cluster = ColumnTransformer([
      ("cat", cat_pipeline, cat_attribs),
      ('num', num_pipeline, num_attributes)
      ], remainder="drop")


    model_name = f'Deep Neural Network with PSA {selected_cluster_column}'
    print(model_name)

    tf.keras.backend.clear_session()

    nn_optimizer = keras.optimizers.SGD(learning_rate=nn_learning_rate, nesterov=True, momentum=0.9)
    model = criar_modelo_dnn(nn_hidden_layers, nn_neurons, nn_activation, nn_optimizer)

    es = EarlyStopping(monitor='val_rmse',
                        mode='min',
                        verbose=1,
                        patience=10,
                        restore_best_weights=True
                        )

    tf_x_train = preprocessor_with_psa_cluster.fit_transform(X_train)
    tf_x_valid = preprocessor_with_psa_cluster.transform(X_valid)

    #tf.config.run_functions_eagerly(True)
    tf.data.experimental.enable_debug_mode()
    history = model.fit(tf_x_train, y_train,
                        epochs=50, callbacks=[es],
                        validation_data=(tf_x_valid, y_valid))
    history_dnn[model_name] = history


    steps = [
      ('preprocessor', preprocessor_with_psa_cluster),
      ('model', model)
    ]
    pipeline = Pipeline(steps)

    predictions = pipeline.predict(test_set)
    #test_rmse = mean_squared_error(test_set['peak_ground_acceleration'], predictions, squared=False)
    test_rmse = root_mean_squared_error(test_set['peak_ground_acceleration'], predictions)
    r2 = r2_score(test_set['peak_ground_acceleration'], predictions)

    confidence = 0.95
    squared_errors = (predictions[:, 0] - test_set['peak_ground_acceleration']) ** 2
    conf_interval = np.sqrt(stats.t.interval(confidence, len(squared_errors) - 1,
                              loc=squared_errors.mean(),
                              scale=stats.sem(squared_errors)))
    conf_range = conf_interval[1] - conf_interval[0]


    experiments[model_name] = [test_rmse, r2, conf_interval[0], conf_interval[1]]

    trained_pipelines[model_name] = pipeline

if not load_trained_models:
  print(trained_pipelines.get('Deep Neural Network with PSA clusters_spectral_means')['model'].summary())
  pd.DataFrame(history_dnn['Deep Neural Network with PSA clusters_spectral_means'].history).plot(
          figsize=(8, 5),  grid=True, xlabel="Epoch",
          style=["r--", "r--.", "b-", "b-*"])
  plt.show()

#xgboost
for selected_cluster_column in cluster_columns:
  print(selected_cluster_column)

  cat_attribs = [selected_cluster_column]

  preprocessor_with_psa_cluster = ColumnTransformer([
    ("cat", cat_pipeline, cat_attribs),
    ('num', num_pipeline, num_attributes)
    ], remainder="drop")

  model_name = f'XGBoost with PSA {selected_cluster_column}'
  print(model_name)

  steps = [
    ('preprocessor', preprocessor_with_psa_cluster),
    ('model', xgb.XGBRegressor(objective='reg:squarederror',
                               colsample_bytree=xbg_colsample_bytree,
                               learning_rate=xbg_learning_rate,
                               max_depth=xbg_max_depth,
                               n_estimators=xbg_n_estimators,
                               subsample=xbg_subsample,
                               gamma = xbg_gamma,
                               min_child_weight = xbg_min_child_weight,
                               reg_alpha = xbg_reg_alpha,
                               reg_lambda = xbg_reg_lambda,
                               random_state=42)) # Use reg:squarederror for regression
  ]

  pipeline = Pipeline(steps)
  test_rmse, r2, pipeline, experiments = model_experiment(train_set, test_set, pipeline, experiments, model_name)
  trained_pipelines[model_name] = pipeline

if not load_trained_models:
  trained_pipelines_backup = copy.deepcopy(trained_pipelines)

"""### Saving results"""

#rm -rf './paper_1_results/'

if not load_trained_models:
  os.makedirs('./paper_1_results_revised/', exist_ok=True)
  experiments_results_filename = './paper_1_results_revised/experiments_results.pickle'
  with open(experiments_results_filename, 'wb') as f:
      pickle.dump(experiments, f)

if not load_trained_models:
  trained_pipelines_path = './paper_1_results_revised/trained_pipelines/'
  os.makedirs(trained_pipelines_path, exist_ok=True)
  #trained_pipelines_copy = trained_pipelines.copy()
  trained_pipelines_copy = copy.deepcopy(trained_pipelines)

  for pipeline_name in list(trained_pipelines_copy.keys()):
    print(pipeline_name)
    pipeline = trained_pipelines_copy.get(pipeline_name)
    filename = f'{trained_pipelines_path}{pipeline_name}.joblib'
    if(pipeline_name.startswith('Deep Neural Network')):
      #model = pipeline.steps.pop(1)
      model = pipeline.named_steps['model']
      model.save(f'{trained_pipelines_path}{pipeline_name}.keras')
      pipeline.steps[1] = ('model', None)
      joblib.dump(pipeline, filename)
      pipeline.steps[1] = ('model', model)
    else:
      joblib.dump(pipeline, filename)

"""## Experiment analysis"""

experiments_results_filename = './paper_1_results_revised/experiments_results.pickle'
with open(experiments_results_filename, 'rb') as f:
    experiments = pickle.load(f)

trained_pipelines_path = './paper_1_results_revised/trained_pipelines/'

trained_pipelines = {}

for file_path in os.listdir(trained_pipelines_path):
    # check if current file_path is a file
    if os.path.isfile(os.path.join(trained_pipelines_path, file_path)):
        if(file_path.split('.')[1]=='joblib'):
          pipeline_name = file_path.split('.')[0]
          print(pipeline_name)
          pipeline_filename_path = f'{trained_pipelines_path}{file_path}'
          print(pipeline_filename_path)
          pipeline = joblib.load(pipeline_filename_path)
          if(pipeline_name.startswith('Deep Neural Network')):
            dnn_model = load_model(f'{trained_pipelines_path}{pipeline_name}.keras', compile = False)
            pipeline.steps.append(['model', dnn_model])
        trained_pipelines[pipeline_name] = pipeline

len(trained_pipelines)

df_experiments = pd.DataFrame(experiments.values())
df_experiments['Description'] = experiments.keys()
df_experiments.columns = ['rmse', 'r2', 'CI Lower Bound','CI Upper Bound' ,'Description']
df_experiments = df_experiments[['Description', 'rmse', 'r2', 'CI Lower Bound','CI Upper Bound' ]]

df_experiments.sort_values(by='rmse')

trained_pipelines.keys()

models_without_psa = ['Linear Regression', 'Polynomial Regression', 'Polynomial ElasticNet', 'Random Forest','Deep Neural Network', 'XGBoost']

fig, axes = plt.subplots(1, len(models_without_psa), figsize=(12, 3), sharey=True)
fig.suptitle('Regression Models without PSA Cluster')

i=0
for model in models_without_psa:
  #pipeline_name = list(trained_pipelines.keys())[i]
  print(model)
  test_pred = trained_pipelines[model].predict(test_set)
  print(len(test_pred.shape))
  if(len(test_pred.shape)>1):
    test_pred = test_pred[:, 0]
  sns.scatterplot(ax=axes[i], x=np.log(test_set['peak_ground_acceleration']), y=np.log(np.abs(test_pred)))

  # --- Linha adicionada para o plot diagonal ---
  # Cria uma linha de referência (y=x)
  lims = [-4, 7]
  axes[i].plot(lims, lims, 'r--', alpha=0.75, zorder=0)
  # -----------------------------------------


  axes[i].set_xlabel('Measured ln(PGA)')
  if(i==0):
    axes[i].set_ylabel('Predicted ln(PGA)')
  axes[i].set_xlim(-4,7)
  axes[i].set_ylim(-4,7)
  axes[i].set_title(model)
  i+=1

plt.tight_layout()

plt.show()

models_with_psa = ['Linear Regression with PSA clusters_spectral_means',
                      'Polynomial Regression with PSA clusters_spectral_means',
                      'Polynomial ElasticNet with PSA clusters_spectral_means',
                      'Random Forest with PSA clusters_spectral_means',
                      'Deep Neural Network with PSA clusters_spectral_means',
                      'XGBoost with PSA clusters_spectral_means'
                      ]

fig, axes = plt.subplots(1, len(models_with_psa), figsize=(12, 3), sharey=True)
fig.suptitle('Regression Models with Three Axis Spectra Cluster')

i=0
for model in models_with_psa:
  index = i+10
  test_pred = trained_pipelines[model].predict(test_set)
  print(model)
  plot_title = model.split('with')[0]
  print(plot_title)

  if(len(test_pred.shape)>1):
    test_pred = test_pred[:, 0]
  sns.scatterplot(ax=axes[i], x=np.log(test_set['peak_ground_acceleration']), y=np.log(np.abs(test_pred)))

  # --- Linha adicionada para o plot diagonal ---
  # Cria uma linha de referência (y=x)
  lims = [-4, 7]
  axes[i].plot(lims, lims, 'r--', alpha=0.75, zorder=0)
  # -----------------------------------------


  axes[i].set_xlabel('Measured ln(PGA)')
  if(i==0):
    axes[i].set_ylabel('Predicted ln(PGA)')
  axes[i].set_xlim(-4,7)
  axes[i].set_ylim(-4,7)
  axes[i].set_title(plot_title)
  i+=1

plt.tight_layout()

plt.show()

"""### Random Forest"""

trained_pipelines.keys()

model_title = 'Random Forest with Three Axis Spectra Cluster'
model_sub_title = 'With Three Axis Spectra Cluster'
pipeline_RF_without_clustering = trained_pipelines['Random Forest']
pipeline_RF_with_clustering = trained_pipelines['Random Forest with PSA clusters_spectral_means']

test_pred1 = pipeline_RF_without_clustering.predict(test_set)
test_pred2 = pipeline_RF_with_clustering.predict(test_set)

percent_error_1 = (test_set['peak_ground_acceleration'] - test_pred1) / test_set['peak_ground_acceleration']
percent_error_2 = (test_set['peak_ground_acceleration'] - test_pred2) / test_set['peak_ground_acceleration']

fig, axes = plt.subplots(1, 2, figsize=(8, 4), sharey=True)
#fig.suptitle('Random Forest')

sns.scatterplot(ax=axes[0], x=test_set['calculated_epicentral_distance'], y=(np.abs(test_set['peak_ground_acceleration'] - test_pred1)))
axes[0].set_xlabel('Epicentral Distance (km)')
axes[0].set_ylabel('PGA error')
axes[0].set_title('Without PSA Cluster')

sns.scatterplot(ax=axes[1], x=test_set['calculated_epicentral_distance'], y=(np.abs(test_set['peak_ground_acceleration'] - test_pred2)))
axes[1].set_xlabel('Epicentral Distance (km)')
axes[1].set_ylabel('PGA error')
axes[1].set_title(model_sub_title)

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(8, 4), sharey=True)
#fig.suptitle('Random Forest')

sns.scatterplot(ax=axes[0], x=test_set['calculated_epicentral_distance'], y=np.abs(percent_error_1))
axes[0].set_xlabel('Epicentral Distance (km)')
axes[0].set_ylabel('PGA error (%)')
axes[0].set_title('Without PSA Cluster')

sns.scatterplot(ax=axes[1], x=test_set['calculated_epicentral_distance'], y=np.abs(percent_error_2))
axes[1].set_xlabel('Epicentral Distance (km)')
axes[1].set_ylabel('PGA error (%)')
axes[1].set_title(model_sub_title)

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(8, 4), sharey=True)
#fig.suptitle('Random Forest')

sns.scatterplot(ax=axes[0], x=test_set['magnitude'], y=(np.abs(test_set['peak_ground_acceleration'] - test_pred1)))
axes[0].set_ylabel('PGA error')
axes[0].set_title('Without PSA Cluster')
axes[0].set_xlabel('Magnitude')

sns.scatterplot(ax=axes[1], x=test_set['magnitude'], y=(np.abs(test_set['peak_ground_acceleration'] - test_pred2)))
axes[1].set_ylabel('PGA error')
axes[1].set_xlabel('Magnitude')
axes[1].set_title('With Three Axis Spectra Cluster')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(8, 4), sharey=True)
#fig.suptitle('Random Forest')

sns.scatterplot(ax=axes[0], x=test_set['magnitude'], y=(np.abs(percent_error_1)))
axes[0].set_ylabel('PGA error (%)')
axes[0].set_title('Without PSA Cluster')
axes[0].set_xlabel('Magnitude')

sns.scatterplot(ax=axes[1], x=test_set['magnitude'], y=(np.abs(percent_error_2)))
axes[1].set_ylabel('PGA error (%)')
axes[1].set_xlabel('Magnitude')
axes[1].set_title('With Three Axis Spectra Cluster')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

# --- Criando dados de exemplo para o código rodar ---
# (Você pode remover esta parte e usar seus dados reais)
# np.random.seed(42)
# test_set = pd.DataFrame({
#     'magnitude': np.random.rand(500) * 4 + 3  # Magnitudes entre 3 e 7
# })
# percent_error_1 = np.random.randn(500) * 20 * (1 / (test_set['magnitude'] - 2.5))
# percent_error_2 = np.random.randn(500) * 10 * (1 / (test_set['magnitude'] - 2.5))
# --- Fim dos dados de exemplo ---


fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True)

# Gráfico 1: Heatmap "Without PSA Cluster"
sns.histplot(
    ax=axes[0],
    x=test_set['magnitude'],
    y=np.abs(percent_error_1),
    bins=30,          # Define a "resolução" do grid
    cbar=True,        # Adiciona a barra de cores
    cmap='viridis'    # Define o esquema de cores
)
axes[0].set_ylabel('PGA error (%)')
axes[0].set_title('Without PSA Cluster')
axes[0].set_xlabel('Magnitude')

# Gráfico 2: Heatmap "With Three Axis Spectra Cluster"
sns.histplot(
    ax=axes[1],
    x=test_set['magnitude'],
    y=np.abs(percent_error_2),
    bins=30,
    cbar=True,
    cmap='viridis'
)
# axes[1].set_ylabel('PGA error (%)') # Removido pois sharey=True já compartilha o eixo
axes[1].set_xlabel('Magnitude')
axes[1].set_title('With Three Axis Spectra Cluster')

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True)
fig.suptitle('Random Forest')

sns.scatterplot(ax=axes[0], x=test_set['clusters_spectral_means'], y=(np.abs(test_set['peak_ground_acceleration'] - test_pred1)))
axes[0].set_ylabel('PGA error')
axes[0].set_title('Without PSA Cluster')
axes[0].set_xlabel('Three Axis Spectra Cluster')

sns.scatterplot(ax=axes[1], x=test_set['clusters_spectral_means'], y=(np.abs(test_set['peak_ground_acceleration'] - test_pred2)))
axes[1].set_ylabel('PGA error')
axes[1].set_xlabel('Three Axis Spectra Cluster')
axes[1].set_title('With Three Axis Spectra Cluster')

fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True)
fig.suptitle('Random Forest')

sns.scatterplot(ax=axes[0], x=test_set['clusters_spectral_means'], y=(np.abs(percent_error_1)))
axes[0].set_ylabel('PGA error (%)')
axes[0].set_title('Without PSA Cluster')
axes[0].set_xlabel('Three Axis Spectra Cluster')

sns.scatterplot(ax=axes[1], x=test_set['clusters_spectral_means'], y=(np.abs(percent_error_2)))
axes[1].set_ylabel('PGA error (%)')
axes[1].set_xlabel('Three Axis Spectra Cluster')
axes[1].set_title('With Three Axis Spectra Cluster')

# Faça o plot
fig, ax1 = plt.subplots(figsize=(7, 4))

# Plote o contorno do México
world.plot(ax=ax1, edgecolor='black', facecolor='green', linewidth=1, zorder=1, alpha=0.5)

# Adicionar marcadores para cada localização
# for lon, lat, name in locations:
#     ax1.plot(lon, lat, 'ko', markersize=3)
#     ax1.text(lon, lat, name, color='w', fontsize=8, ha='right', va='bottom')

# Seu scatterplot original
g = sns.scatterplot(ax=ax1,
                    data=df_com_clusters,
                    x='station_longitude',
                    y='station_latitude',
                    #size='magnitude',
                    #hue='magnitude',
                    hue='clusters_spectral_means',
                    #sizes=(40, 400),
                    s=50,
                    zorder=2,
                    #palette=sns.color_palette("Reds", as_cmap=True),
                    #marker=(8,1,0)
                    )


# Definir intervalos para os ticks
ax1.xaxis.set_major_locator(ticker.MultipleLocator(2))  # Intervalo de 2 graus
ax1.yaxis.set_major_locator(ticker.MultipleLocator(1))  # Intervalo de 1 grau

# Formatar os labels com o símbolo de grau
def longitude_formatter(x, p):
    return f'{x}°W'

def latitude_formatter(x, p):
    return f'{x}°N'

ax1.xaxis.set_major_formatter(ticker.FuncFormatter(longitude_formatter))
ax1.yaxis.set_major_formatter(ticker.FuncFormatter(latitude_formatter))

# Rotacionar os labels do eixo x para melhor legibilidade
plt.xticks(rotation=45)

# Ajustar os limites e labels
ax1.set_xlabel('Longitude', labelpad=10)
ax1.set_ylabel('Latitude', labelpad=10)
plt.xlim([-106, -90])
plt.ylim([13, 22])

plt.legend(frameon=True, title='Station Cluster')


# Ajustar o layout para evitar cortes
plt.tight_layout()

plt.show()

# Faça o plot
fig, ax1 = plt.subplots(figsize=(6, 4))

# Plote o contorno do México
world.plot(ax=ax1, edgecolor='black', facecolor='green', linewidth=1, zorder=1, alpha=0.5)

# Adicionar marcadores para cada localização
for lon, lat, name in locations:
    ax1.plot(lon, lat, 'ko', markersize=3)
    ax1.text(lon, lat, name, color='w', fontsize=8, ha='right', va='bottom')

# Seu scatterplot original
g = sns.scatterplot(ax=ax1,
                    data=df_com_clusters,
                    x='station_longitude',
                    y='station_latitude',
                    #size='magnitude',
                    #hue='magnitude',
                    hue='clusters_spectral_means',
                    #sizes=(40, 400),
                    s=50,
                    zorder=2,
                    #palette=sns.color_palette("Reds", as_cmap=True),
                    #marker=(8,1,0)
                    )


# Definir intervalos para os ticks
ax1.xaxis.set_major_locator(ticker.MultipleLocator(2))  # Intervalo de 2 graus
ax1.yaxis.set_major_locator(ticker.MultipleLocator(1))  # Intervalo de 1 grau

# Formatar os labels com o símbolo de grau
def longitude_formatter(x, p):
    return f'{x}°W'

def latitude_formatter(x, p):
    return f'{x}°N'

ax1.xaxis.set_major_formatter(ticker.FuncFormatter(longitude_formatter))
ax1.yaxis.set_major_formatter(ticker.FuncFormatter(latitude_formatter))

# Rotacionar os labels do eixo x para melhor legibilidade
#plt.xticks(rotation=45)

# Ajustar os limites e labels
ax1.set_xlabel('Longitude', labelpad=10)
ax1.set_ylabel('Latitude', labelpad=10)
plt.xlim([-99, -97.5])
plt.ylim([18, 19.2])


#plt.legend(frameon=True, title='Three Axis Spectra Cluster')
plt.legend(frameon=True, title='Cluster')


# Ajustar o layout para evitar cortes
plt.tight_layout()

plt.show()

df_com_clusters.clusters_spectral_means.value_counts()

df_com_clusters[df_com_clusters.clusters_spectral_means == 3].soil_type.value_counts()

test_set

simulation = test_set[test_set.index == 1083].copy()

simulation.iloc[0]

pipeline_RF_with_clustering.predict(simulation)

simulation.columns

simulation.clusters_spectral_means

simulation = simulation.reset_index(drop=True)
simulation

pred = pipeline_RF_with_clustering.predict(simulation)[0]
simulation['pga_pred'] = pred

for i in range(0,4):
  simulation2 = simulation[simulation.index == 0].copy()
  simulation2.clusters_spectral_means = i
  pred = pipeline_RF_with_clustering.predict(simulation2)[0]
  simulation2['pga_pred'] = pred
  simulation = pd.concat([simulation, simulation2])
  simulation = simulation.reset_index(drop=True)

simulation

fig, ax = plt.subplots(figsize=(5, 4)) # width and height in inches

p = sns.barplot(data=simulation, x="clusters_spectral_means", y="pga_pred", ax=ax)
p.set(xlabel="Three Axis Spectra Cluster")
p.set(ylabel="PGA Predicted")

plt.tight_layout()
plt.show()



